### ISSUE TITLE
Import/export on B2B customer

### ISSUE THREAD

**Issue by jeanmonod** [orocrm/crm#100]
As contact and account support import/export, we would like to see the same on B2B customer. Thanks

**Comment by akuzmenko-magecore** [comment]
Hi @jeanmonod,
We have this improvement planned for future releases.
Thank you for you feedback

**Comment by rodolfobandeira** [comment]
Hi There! 
I'd like to add 'Order' in this request. Thanks!

**Comment by rodolfobandeira** [comment]
@alsma-magecore Do we have today any alternative to import B2B Customers? Can I do this using REST ORO-API?

Thank you!

**Comment by jeanmonod** [comment]
@rodolfobandeira no, we didn't find an alternative as the project is currently "on hold", but we are going to face the same issue in few weeks. @akuzmenko-magecore Do you have a release time frame that you can communicate us? Are we talking about weeks, months or years? Thanks for the feedbacks

**Comment by rodolfobandeira** [comment]
@jeanmonod 
I know the next Webinar is gonna be "Import/Export"

February 10, 2015 (9:00 am to 10:00 am PST)
Integrated your data into OroCRM: import/export

**Comment by synolia** [comment]
Hello all,
Some news about this next feature ?

**Comment by rodolfobandeira** [comment]
Hi @synolia 

Check this webinar from @sergeyz : 
https://www.youtube.com/watch?v=OcJCyBqo6Hk

https://github.com/sergeyz/crm-b2bcustomer-import

**Comment by DimaSoroka** [comment]
We are including it in the next release, should be available in master till the end of this week.

**Comment by sergeyz** [comment]
Available since 1.7
