### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by michaeld23** [orocrm/crm#101]
Hello !

I am trying to install the application as described in https://github.com/orocrm/crm-application but I always encounters the following problem during step 3 (via install.php on browser): 

![image](https://cloud.githubusercontent.com/assets/6111939/5587692/dc58246a-90f2-11e4-85fd-2dcd222158c0.png)

In the oro_install.log I can see this error :

![image](https://cloud.githubusercontent.com/assets/6111939/5587670/21694490-90f2-11e4-8263-db899b17ab4a.png)

I am installing it on a xampp server - windows 7. I also tryied to install it by cmd but it doesn't work either. I have made some researches into the existing issues but didn't find the solution to my problem. 

I hope that maybe you can help me through this issue. 
If you need any complementary information I am of course at your disposal.

Thank you in advance

**Comment by arbitbet** [comment]
Hello,

Did you have installed OroCRM before in your web root directory?
Please try to clear cache before install(clear folder app/cache).
I installed OroCRM on a xampp server Win7. I did not have any problem.
I hope "clear cache" helps you.

Thanks.

**Comment by michaeld23** [comment]
Hello, 
Thank you for answering me. I just found the problem yesterday and solved it.
In the file Oro/Bundle/InstallerBundler/Process/Step/ShemaStep.php at line 11 there is a set_time_limit(600); which I commented and then it worked perfectly. I suppose some operation took too long. I had a clue by checking my php error log file. It seems strange because I first checked my localhost configuration for time limit which was set to 0. So I had a rough time finding this specific problem but I am not sure it is the better one. 

If it is ok for you I will close this issue. 

Now I am trying to deploy my application and I will maybe come back to you if I have some kind of other difficulties.

**Comment by sergeyz** [comment]
Hi, @michaeld23!
Do you use master branch? Please try 1.5.0 tag `git checkout tags/1.5.0`

**Comment by michaeld23** [comment]
Hi @sergeyz!

Sorry for the delay of my answer. Yes I used master branch. I just tryied 1.5.0 tag as you asked  but it didn't work in both web and console install methods. The same problem  as illustrated in my first post happened during this test.

I deployed my application on a distant server with no problem. But I had this following issue loading the french language pack : 

![image](https://cloud.githubusercontent.com/assets/6111939/5883703/32cf2f5e-a355-11e4-94d6-0ac37b693761.png)

This file seems to be in a wrong format with these two parameters at line 1 and 117 : %subject% 

A few weeks before I had no problem with this operation. Can you solve this problem or have I to maybe open another issue ?

**Comment by sergeyz** [comment]
For xampp installation please drop caches and database manually.

> Can you solve this problem or have I to maybe open another issue ?

We are working on that issue, thanks!

**Comment by artml** [comment]
This issue has been fixed in https://github.com/orocrm/platform/issues/225
