### ISSUE TITLE
[Q] Customized channel autocomplete dropdown

### ISSUE THREAD

**Issue by excelwebzone** [orocrm/crm#102]
I'm trying to customize an autocomplete channel dropdown. Here is what I have so far:

```php
class Type extends ExtendType implements ChannelAwareInterface
{
    use IntegrationEntityTrait, OriginTrait, ChannelEntityTrait;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=255)
     */
    protected $name;

    /**
     * @var integer
     *
     * @ORM\Column(name="level", type="integer", nullable=true)
     */
    protected $level;
   //...
}
```
```php
class TypeSelectType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults([
            'configs' => [
                'placeholder' => 'acme.type.form.choose_type',
            ],
            'autocomplete_alias' => 'types',
            'grid_name'          => 'demo-type-grid',
            'create_form_route'  => 'demo_type_create',
            'create_enabled'     => true,
        ]);
    }

    /**
     * {@inheritdoc}
     */
    public function getParent()
    {
        return 'oro_entity_create_or_select_inline_channel_aware';
    }

    /**
     * {@inheritdoc}
     */
    public function getName()
    {
        return 'demo_type_select';
    }
}
```
What I'm trying to do is when choosing a type it will set the input field with "data-level" of the selected type. Can anyone help me this it? Thanks.

**Comment by excelwebzone** [comment]
Hi @alsma-magecore, can you please see if you can provide me with an easy solution. Thanks.

**Comment by alsma-magecore** [comment]
Hey @excelwebzone !

Not sure that I've got an idea, `oro_entity_create_or_select_inline_channel_aware` field type was designed in order to be able to fetch data from field in the same form and pass its value as channelId option into search/datagrid request. Do you want to use your custom field `level` instead of channel in the same scenario? If so you have to implement search handler and datagrid that will be able to handle `level` attribute correctly

**Comment by excelwebzone** [comment]
No, the intentions is to reload the dropdown based on the channel, since each channel might have similar types which can be confuse when selecting.. the idea is to generate a <select> like this:
```html
<select name="form...._type">
    <option value="1" level="1">type1</option>
    <option value="2" level="1">type2</option>
    <option value="3" level="2">type3</option>
    <option value="4" level="3">type4</option>
</select>
```
Q: is there a nice way to catch the channel change event and reload the select with options?

**Comment by excelwebzone** [comment]
@alsma-magecore Any luck?
