### ISSUE TITLE
PHP Executable could not be found

### ISSUE THREAD

**Issue by fdrechsler** [orocrm/crm#105]
Hey Guys,

my System Information:
Ubuntu 12.04
PHP 5.5.14
PLESK 12

I am trying to install OroCRM on a subdomain.
Step1 System Requirements Check: Everything is green
Step2 - Everything good
Step3: Failes at "Clear cache before database initialization"

*app/logs/oro_install.log* says:
```
 [RuntimeException]                                                                             
  The php executable could not be found, add it to your PATH environment variable and try again 
```

PHP Info
```
_SERVER["PHP_PATH"]	/usr/bin/php
_SERVER["PHP_BINARY"]	/usr/bin/php
_SERVER["ORO_PHP_PATH"]	/usr/bin/php
```

vhosts.conf
```
SetEnv ORO_PHP_PATH /usr/bin/php
SetEnv PHP_BINARY /usr/bin/php
SetEnv PHP_PATH /usr/bin/php
```

No PHP Errors

What to do?

**Comment by rodolfobandeira** [comment]
Try to type this in your console: 
``` bash
echo $PATH
```
If you don't see any php path, you need to add on it.

**Comment by fdrechsler** [comment]
# echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

This is okay, isnt it?

**Comment by fdrechsler** [comment]
Solved. 
PHP.INI open_basedir was restricted. So it did not had access to /usr/bin
