### ISSUE TITLE
Account Rest Api - missing limit and page

### ISSUE THREAD

**Issue by majoskorec** [orocrm/crm#106]
hi

there are missing limit and page params in handleGetListRequest
https://github.com/orocrm/crm/blob/master/src/OroCRM/Bundle/AccountBundle/Controller/Api/Rest/AccountController.php#L52

**Comment by Krushelnitskiy** [comment]
Thank you for issue. We begin work to fix this problem. We will reply to you as soon as possible.

**Comment by sergeyz** [comment]
Fixed, thanks!

https://github.com/orocrm/crm/blob/master/src/OroCRM/Bundle/AccountBundle/Controller/Api/Rest/AccountController.php#L52
