### ISSUE TITLE
Form builder error

### ISSUE THREAD

**Issue by kzweb** [orocrm/crm#107]
Url: http://localhost/crm/web/app_dev.php/channel/create

PHP errors:

Notice: Undefined index: disabled in C:\xampp\htdocs\crm\vendor\symfony\symfony\src\Symfony\Component\Form\Extension\Core\Type\BaseType.php on line 35

Notice: Undefined index: auto_initialize in C:\xampp\htdocs\crm\vendor\symfony\symfony\src\Symfony\Component\Form\Extension\Core\Type\BaseType.php on line 36

Notice: Undefined index: required in C:\xampp\htdocs\crm\vendor\symfony\symfony\src\Symfony\Component\Form\Extension\Core\Type\FormType.php on line 47

Notice: Undefined index: error_bubbling in C:\xampp\htdocs\crm\vendor\symfony\symfony\src\Symfony\Component\Form\Extension\Core\Type\FormType.php on line 48

Notice: Undefined index: empty_data in C:\xampp\htdocs\crm\vendor\symfony\symfony\src\Symfony\Component\Form\Extension\Core\Type\FormType.php on line 49

Notice: Undefined index: property_path in C:\xampp\htdocs\crm\vendor\symfony\symfony\src\Symfony\Component\Form\Extension\Core\Type\FormType.php on line 50

Notice: Undefined index: mapped in C:\xampp\htdocs\crm\vendor\symfony\symfony\src\Symfony\Component\Form\Extension\Core\Type\FormType.php on line 51

Notice: Undefined index: by_reference in C:\xampp\htdocs\crm\vendor\symfony\symfony\src\Symfony\Component\Form\Extension\Core\Type\FormType.php on line 52

Notice: Undefined index: inherit_data in C:\xampp\htdocs\crm\vendor\symfony\symfony\src\Symfony\Component\Form\Extension\Core\Type\FormType.php on line 53

Notice: Undefined index: compound in C:\xampp\htdocs\crm\vendor\symfony\symfony\src\Symfony\Component\Form\Extension\Core\Type\FormType.php on line 54

Notice: Undefined index: compound in C:\xampp\htdocs\crm\vendor\symfony\symfony\src\Symfony\Component\Form\Extension\Core\Type\FormType.php on line 57

Notice: Undefined index: method in C:\xampp\htdocs\crm\vendor\symfony\symfony\src\Symfony\Component\Form\Extension\Core\Type\FormType.php on line 58

Stack trace:

![stack trace](https://cloud.githubusercontent.com/assets/10473169/6545492/c17ca968-c568-11e4-9380-ad80074157bd.jpg)

**Comment by artml** [comment]
@kzweb do you still experience this error?
