### ISSUE TITLE
Error 500 when click on "Develop" - Sales Process

### ISSUE THREAD

**Issue by rodolfobandeira** [orocrm/crm#108]
Hello!
I'm stuck in a problem. When I click in "Develop" button on OroCRM/Sales Process, I'm getting error 500 on the widget. So, I tried to replicate the same problem in my production server and I can't see anything wrong on our Log Files. I'm getting this error on oro-cloud.com witch is running CRM 1.6.1, Platform 1.6.1, and EE 1.8.1 (The same in our own instance)

This is an example of url getting problems:
http://XXXXXXX.oro-cloud.com/workflowwidget/transition/edit/attributes/378/develop?_widgetContainer=dialog&_wid=64685be8-a285-4cdf-b3b5-85ea3f335879

Any clue to help me to solve this problem?
Thank you..

**Comment by rgrebenchuk** [comment]
Hi,
Could you share php log with occurred exception ?

**Comment by rodolfobandeira** [comment]
Hi @rgrebenchuk 
I don't have access to logs from oro-cloud.com

**Comment by rodolfobandeira** [comment]
@rgrebenchuk You can see more details on http://support.orocrm.com (Reference: OSD-66)
