### ISSUE TITLE
Email Campaign Sending E-Mails to unsubscribed Leads on Marketing list

### ISSUE THREAD

**Issue by ahrrikis** [orocrm/crm#109]
Hi,

using oroCRM 1.5 we are facing the problem that Email Campaigns are sending emails also to unsubscribed and removed members of a marketing list.
Meanwhile just the subscribed members of the marketing list are displayed before sending, during sending emails are also sent to those, who are unsubscribed. 
It doesnt matter if the mails are send from webinterface or cronjob. We are using SMTP for mailtransport. 

Do you have any suggestions how to solve this? 

Thanks

**Comment by DimaSoroka** [comment]
Thanks for pointing this out, we fixed this issue and will release the fix soon.

**Comment by artml** [comment]
@ahrrikis we have fixed this around 1.7 version, can you please check if the issue persists? Thank you.

**Comment by ahrrikis** [comment]
Yes it is persisting in Version 1.7 still. We have completly changed E-Mail sending though, I cant check if it still exists.

**Comment by artml** [comment]
@ahrrikis please do.

**Comment by artml** [comment]
closed due to no feedback
