### ISSUE TITLE
oro:cron:analytic:calculate Crashing the PHP-FPM 100% CPU

### ISSUE THREAD

**Issue by rodolfobandeira** [orocrm/crm#110]
Hello guys!

I still need to investigate what exactly the `oro:cron:analytic:calculate` command is doing but I decided to post this issue if someone have any clue please let me know.

After I applied RFM metrics in a huge (5 years of data from a big magento website) I could see 2 process consuming `100% of cpu` and crashing my `php-fpm`. Only came back when I killed the process and restarted my fpm process. So, I didn't see nothing on my log files (Production environment).

```
app/console --env=prod oro:cron:analytic:calculate --jms-job-id=16405 --channel=7
app/console --env=prod oro:cron:analytic:calculate --jms-job-id=16406 --channel=7
```

![analytic:crash](http://s10.postimg.org/mr7kpkord/Screen_Shot_2015_03_27_at_4_07_04_PM.png)

The result after this command was a `502 Gateway Error` on my Nginx. Do you guys know something about this? Any clue or tip to solve it? Any recommendation using RFM Metrics? Any date range limit to run it safely?

Thank you!

**Comment by DimaSoroka** [comment]
hi @rodolfobandeira 

We fixed a couple of performance issues already and have one more to fix. Please let us know your version number as well.

**Comment by rodolfobandeira** [comment]
Hi @DimaSoroka 

Thank you for your answer. My current crm-application are running on these versions:
- oro/platform: 1.6.0
- oro/crm: 1.6.0
- oro/crm-enterprise: 1.8.0

Just other information. Yesterday I started RFM metrics again and it still running. 20hours running and didn't finish yet. I have a instance running on AWS with 4 CPU's and all of them are running on 90% of CPU utilization.  Is it normal? Can you guys please verify if there is something wrong with the metric rules? 

![RFM metrics](http://s2.postimg.org/m0mwb6vu1/Screen_Shot_2015_03_31_at_9_09_04_AM.png)

Client's information:
- 170k orders
- 30k carts
- 96k web customers

**Comment by rodolfobandeira** [comment]
Just a heads up, after 40hours.. I'm almost on 50%. I got the progress with this query:

```sql
select 
    count(*) as total 
from 
    orocrm_magento_customer m 
where 
    m.channel_id = 7 
and 
    (m.rfm_frequency > 0 OR m.rfm_recency > 0 OR m.rfm_monetary > 0);
```

**Comment by rodolfobandeira** [comment]
Fixed
