### ISSUE TITLE
Wrong currency in account order overview

### ISSUE THREAD

**Issue by falcovandermaden** [orocrm/crm#111]
OroCRM is setup in a specific currency. What will happen if orders are imported with different currencies than that?

This question came up because I imported Magento orders in EURO and had setup OroCRM in Dollars. Order overview was still correct but the order overview in Account wasn't. It showed the amounts in DOLLARS. € 8,99 vs $ 8,99

**Comment by artml** [comment]
@falcovandermaden we do not support multi-currency in OroCRM yet, so all amounts will be imported as is regardless of the currency. E.g. if you have three orders for $500, €500, and £500 in Magento, all three will be treated as $500 ones in OroCRM that is configured for dollars.

We have plans to add proper support for multiple currencies, it's just hard to tell when exactly. Perhaps it will come when we develop integration with OroCommerce (~Q3 this year) that has multi-currency support. Please follow our updates.

**Comment by artml** [comment]
no further questions so i'm closing it
