### ISSUE TITLE
Tasks do not render in activity lists

### ISSUE THREAD

**Issue by codedealer** [orocrm/crm#113]
I get js type error 'string is not a function' on frontend when render tasks in activity list. Maybe it's just me, but looks like the second argument is missing in template function of underscore [here](https://github.com/orocrm/crm/blob/master/src/OroCRM/Bundle/TaskBundle/Resources/views/Task/js/activityItemTemplate.js.twig#L19).
Passing null as the second argument seem to fix this since data is passed in function call and not as argument.

**Comment by Grygir** [comment]
What CRM version do you use?
This issue might be caused by getting out of sync the Underscore lib and a template. In version 1.7.0 they changed:

> Underscore templates no longer accept an initial data object. `_.template` always returns a function now.

Do you still experience this issue?

**Comment by codedealer** [comment]
Grygir, I was able to fix it by making changes in activityItemTemplate.js.twig according to Underscore documentation. Yes, you are correct that this is caused by underscore.js being upgraded. 

I am closing it right now as it seems it has nothing to do with OroCRM itself and is caused by version conflict.
