### ISSUE TITLE
Problem with dependency installation (zend-stdlib)

### ISSUE THREAD

**Issue by pgrzywacz** [orocrm/crm#116]
Hello,

I am unable to install the ORM. During composer install there is an error with zend-stdlib download:

```
  - Installing zendframework/zend-stdlib (2.1.5)
    Downloading: Connecting...    Failed to download zendframework/zend-stdlib from dist: The "https://api.github.com/repos/zendframework/Component_ZendStdlib/zipball/1b21f3f9a206bd79da3c660b8c550b50d88f3a7e" file could not be downloaded (HTTP/1.1 404 Not Found)
    Now trying to download from source
  - Installing zendframework/zend-stdlib (2.1.5)
    Cloning 1b21f3f9a206bd79da3c660b8c550b50d88f3a7e


                                                                                                                  
  [RuntimeException]                                                                                              
  Failed to clone git@github.com:zendframework/Component_ZendStdlib.git via git, https, ssh protocols, aborting.  
  - git://github.com/zendframework/Component_ZendStdlib.git                                                       
    Cloning into '/var/www/OroCRM/vendor/zendframework/zend-stdlib/Zend/Stdlib'...                                
    fatal: remote error:                                                                                          
      Repository not found.                                                                                       
  - https://github.com/zendframework/Component_ZendStdlib.git                                                     
    Cloning into '/var/www/OroCRM/vendor/zendframework/zend-stdlib/Zend/Stdlib'...                                
    remote: Invalid username or password.                                                                         
    fatal: Authentication failed for 'https://github.com/zendframework/Component_ZendStdlib.git/'                 
  - git@github.com:zendframework/Component_ZendStdlib.git                                                         
    Cloning into '/var/www/OroCRM/vendor/zendframework/zend-stdlib/Zend/Stdlib'...                                
    Permission denied (publickey).                                                                                
    fatal: Could not read from remote repository.                                                                 
                                                                                                                  
    Please make sure you have the correct access rights                                                           
    and the repository exists.         
```                                                                           
                                                                                                                  
It seems to be a very old version of the library which is no longer available.

**Comment by sergeyz** [comment]
Hi, @pgrzywacz!

2.1.5 reference is https://github.com/zendframework/zend-stdlib/commit/0027339961ad3d49f91ee092e23f7269c18cb470

please try to clean composer caches using `composer clear-cache`

**Comment by pgrzywacz** [comment]
I'm installing it on a fresh virtual machine so it shouldn't be an issue. However I did try to to clear the cache:
```
root@template-debian8-ldap:/var/www/OroCRM# composer clear-cache
Clearing cache (cache-dir): /root/.composer/cache
Clearing cache (cache-files-dir): /root/.composer/cache/files
Clearing cache (cache-repo-dir): /root/.composer/cache/repo
Cache directory does not exist (cache-vcs-dir): 
All caches cleared.
```
However composer install still fails with exactly the same error, even after removing vendor directory and redownloading everything.

**Comment by sergeyz** [comment]
Please run 'composer update' instead of `composer install`

**Comment by pgrzywacz** [comment]
composer update works, thanks

**Comment by lucasaba** [comment]
Another possible solution is to run ```composer require zendframework/zend-code 2.1.5``` in this way you can still ```install``` instead of ```update```

**Comment by apoberez** [comment]
Hi @lucasaba! This way you'll have further problems with project installation. Working solution is  <code>composer update --no-dev</code> as @sergeyz suggests.

**Comment by rnogueir** [comment]
I had the same problem trying to install version 1.7.0 and nothing of the above could solve the issue.

After removing the installation and cloning the newer version 1.8.2 solved the problem.

**Comment by shubham-babu** [comment]
i am unable to install zend-modulemanager during installation it's getting a error 

The "https://repo.packagist.org/packages.json" file could not be downloaded: SSL operation failed with code 1. OpenSSL Error messages:
error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
Failed to enable crypto
failed to open stream: operation failed
https://repo.packagist.org could not be fully loaded, package information was loaded from the local cache and may be out of date
Using version ^2.8 for zendframework/zend-modulemanager
./composer.json has been updated
Loading composer repositories with package information
The "https://repo.packagist.org/packages.json" file could not be downloaded: SSL operation failed with code 1. OpenSSL Error messages:
error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
Failed to enable crypto
failed to open stream: operation failed
https://repo.packagist.org could not be fully loaded, package information was loaded from the local cache and may be out of date
Updating dependencies (including require-dev)
Package operations: 5 installs, 0 updates, 0 removals
  - Installing zendframework/zend-stdlib (3.2.1): Downloading (failed)
Downloading (failed)
Downloading (failed)    Failed to download zendframework/zend-stdlib from dist: The "https://api.github.com/repos/zendframework/zend-stdlib/zipball/66536
SSL operation failed with code 1. OpenSSL Error messages:
error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
Failed to enable crypto
failed to open stream: operation failed
    Now trying to download from source
  - Installing zendframework/zend-stdlib (3.2.1): Cloning 6653600672


  [RuntimeException]
  Failed to clone https://github.com/zendframework/zend-stdlib.git, git was not found, check that it is installed and in your PATH env.

  'git' is not recognized as an internal or external command,
