### ISSUE TITLE
MagentoConnectorBundle causes UTF-8 BOM error

### ISSUE THREAD

**Issue by HirokazuNishi** [orocrm/crm#121]
Hi,
I recently faced an issue. When I executed sync job against my customer's Magento. I set up integration settings and executed syncing.
At the beginning, syncing process seemed to work fine, and I waited. After one hour later, sync process was stopped by SOAP error.
The error message is "looks like we got no XML document".
I copied xml document that was reported as error and parsed via simpleXML. Then I got error. It seemed valid XML document, but it included something wrong.
Finally I found the solution from this url.

https://www.mikemackintosh.com/fixing-soap-exception-no-xml/

I think this issue is caused by UTF-8 BOM.

**Comment by artml** [comment]
@HirokazuNishi do you still face this issue?
