### ISSUE TITLE
Piwik tracking code not replacing [user_identifier]

### ISSUE THREAD

**Issue by viktorix** [orocrm/crm#122]
This may be by design and how it's supposed to be, but it looks like [user_identifier] should have been replaced with proper ID inside tracking for a specific website:
![Piwik](http://i.imgur.com/tAH73Ug.png)

Found on this page:
/tracking/website/view/1

Thought I report it.

**Comment by sergeyz** [comment]
Hi, @viktorix!

When you inject this code to your website you should provide this user identifier by yourself. It will be used as originId in OroCRM
