### ISSUE TITLE
Magento bridge : trouble with carts / orders sync

### ISSUE THREAD

**Issue by antoineBaret** [orocrm/crm#123]
hello,

I've set an environment with OroCRM (i don't know the version but I saw on Git that it was commit 73db4fb232) an Magento CE1.9

I've gotsyncing problems when OroCRM tries to synchronize carts and orders. This is what I get from the jobs logs : 

Command 	oro:magento:initial:sync --integration-id=1 --skip-dictionary -v

Run initial sync for "Demo Web store" integration.
Syncing connector customer_initial starting 2014-07-17 08:52:29 interval 7 days
Start processing "customer_initial" connector
Looking for batch
found 0 entities
Stats: read [0], processed [0], updated [0], added [0], deleted [0], invalid entities: [0]
Syncing connector cart_initial starting 2014-11-27 08:52:29 interval 7 days
Start processing "cart_initial" connector
Looking for batch
Stats: read [0], processed [0], updated [0], added [0], deleted [0], invalid entities: [0]
Errors were occurred:

[message]           Call to undefined method Mage_Catalog_Model_Product_Type_Simple::getUsedProducts()
[request]           <?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="urn:Magento" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" SOAP-ENV:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><SOAP-ENV:Body><ns1:oroQuoteList><sessionId xsi:type="xsd:string">7f47a4e1172919e1b054a4e667030c51</sessionId><filters xsi:type="ns1:filters"><complex_filter SOAP-ENC:arrayType="ns1:complexFilter[2]" xsi:type="ns1:complexFilterArray"><item xsi:type="ns1:complexFilter"><key xsi:type="xsd:string">created_at</key><value xsi:type="ns1:associativeEntity"><key xsi:type="xsd:string">from</key><value xsi:type="xsd:string">2014-11-20 08:47:29</value></value></item><item xsi:type="ns1:complexFilter"><key xsi:type="xsd:string">created_at</key><value xsi:type="ns1:associativeEntity"><key xsi:type="xsd:string">to</key><value xsi:type="xsd:string">2014-11-27 08:47:29</value></value></item></complex_filter></filters><pager xsi:type="ns1:pager"><page xsi:type="xsd:string">1</page><pageSize xsi:type="xsd:string">100</pageSize></pager></ns1:oroQuoteList></SOAP-ENV:Body></SOAP-ENV:Envelope>

[response]          <?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"><SOAP-ENV:Body><SOAP-ENV:Fault><faultcode>SOAP-ENV:Server</faultcode><faultstring>Call to undefined method Mage_Catalog_Model_Product_Type_Simple::getUsedProducts()</faultstring></SOAP-ENV:Fault></SOAP-ENV:Body></SOAP-ENV:Envelope>

[code]              500

Completed

**Comment by DimaSoroka** [comment]
It looks as your instance API is affected by some extension on Magento side, could you please check if WSDL is generated by calling http://magentohost/api/v2_soap?wsdl=1?

**Comment by jpmarin** [comment]
Hi I am receiving the same error here

I tried with a clean magento install and a clean orocrm install with demo data only.

Thanks!

**Comment by jpmayoral** [comment]
Hello! I've encountered the problem with oro sync, and it's on Configurable Swatches feature. The quick solution I've found it is to disable Configurable Swatches option from backend.

I think it's a core bug with this issue but I don't know if it's a Magento issue or an Oro CRM issue.

Kind regards!

**Comment by DimaSoroka** [comment]
Are you using some extension for Configurable Swatches?

**Comment by jpmarin** [comment]
We are using standard swatches functionality in Magento CE 1.9

Regards,

**Comment by Goeny** [comment]
I am on Magento CE 1.7
Same issue here.

```
Run initial sync for "Magento Integration" integration.
Syncing connector customer_initial starting 2015-10-02 13:52:18 interval 7 days
Start processing "customer_initial" connector
Looking for batch
found 0 entities
Stats: read [0], processed [0], updated [0], added [0], deleted [0], invalid entities: [0]
Syncing connector cart_initial starting 2015-10-02 13:52:18 interval 7 days
Start processing "cart_initial" connector
Looking for batch
found 0 entities
Stats: read [0], processed [0], updated [0], added [0], deleted [0], invalid entities: [0]
Syncing connector order_initial starting 2015-10-02 13:52:18 interval 7 days
Start processing "order_initial" connector
Looking for batch
found 0 entities
Stats: read [0], processed [0], updated [0], added [0], deleted [0], invalid entities: [0]
Syncing connector customer_initial starting 2015-09-25 13:52:18 interval 7 days
Start processing "customer_initial" connector
Looking for batch
found 1 entities
Loading Customer by id: 4855
Stats: read [1], processed [1], updated [0], added [1], deleted [0], invalid entities: [0]
Syncing connector cart_initial starting 2015-09-25 13:52:18 interval 7 days
Start processing "cart_initial" connector
Looking for batch
found 1 entities
Loading Cart by id: 30516
Stats: read [1], processed [0], updated [0], added [0], deleted [0], invalid entities: [1]
Syncing connector order_initial starting 2015-09-25 13:52:18 interval 7 days
Start processing "order_initial" connector
Looking for batch
found 0 entities
Stats: read [0], processed [0], updated [0], added [0], deleted [0], invalid entities: [0]
Syncing connector customer_initial starting 2015-09-18 13:52:18 interval 7 days
Start processing "customer_initial" connector
Looking for batch
found 0 entities
Stats: read [0], processed [0], updated [0], added [0], deleted [0], invalid entities: [0]
Syncing connector cart_initial starting 2015-09-18 13:52:18 interval 7 days
Start processing "cart_initial" connector
Looking for batch
found 0 entities
Stats: read [0], processed [0], updated [0], added [0], deleted [0], invalid entities: [0]
Syncing connector order_initial starting 2015-09-18 13:52:18 interval 7 days
Start processing "order_initial" connector
Looking for batch
found 0 entities
Stats: read [0], processed [0], updated [0], added [0], deleted [0], invalid entities: [0]
Syncing connector customer_initial starting 2015-09-11 13:52:18 interval 7 days
Start processing "customer_initial" connector
Looking for batch
found 0 entities
Stats: read [0], processed [0], updated [0], added [0], deleted [0], invalid entities: [0]
Syncing connector cart_initial starting 2015-09-11 13:52:18 interval 7 days
Start processing "cart_initial" connector
Looking for batch
found 0 entities
Stats: read [0], processed [0], updated [0], added [0], deleted [0], invalid entities: [0]
Syncing connector order_initial starting 2015-09-11 13:52:18 interval 7 days
Start processing "order_initial" connector
Looking for batch
found 0 entities
Stats: read [0], processed [0], updated [0], added [0], deleted [0], invalid entities: [0]
Syncing connector customer_initial starting 2015-09-04 13:52:18 interval 7 days
Start processing "customer_initial" connector
Looking for batch
found 0 entities
Stats: read [0], processed [0], updated [0], added [0], deleted [0], invalid entities: [0]
Syncing connector cart_initial starting 2015-09-04 13:52:18 interval 7 days
Start processing "cart_initial" connector
Looking for batch
Stats: read [0], processed [0], updated [0], added [0], deleted [0], invalid entities: [0]
Errors were occurred:

[message]           Internal Server Error
[request]           <?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="urn:Magento" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" SOAP-ENV:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><SOAP-ENV:Body><ns1:oroQuoteList><sessionId xsi:type="xsd:string">6ed910003451db39745230570f18d12d</sessionId><filters xsi:type="ns1:filters"><complex_filter SOAP-ENC:arrayType="ns1:complexFilter[3]" xsi:type="ns1:complexFilterArray"><item xsi:type="ns1:complexFilter"><key xsi:type="xsd:string">store_id</key><value xsi:type="ns1:associativeEntity"><key xsi:type="xsd:string">in</key><value xsi:type="xsd:string">1</value></value></item><item xsi:type="ns1:complexFilter"><key xsi:type="xsd:string">created_at</key><value xsi:type="ns1:associativeEntity"><key xsi:type="xsd:string">from</key><value xsi:type="xsd:string">2015-08-28 13:47:18</value></value></item><item xsi:type="ns1:complexFilter"><key xsi:type="xsd:string">created_at</key><value xsi:type="ns1:associativeEntity"><key xsi:type="xsd:string">to</key><value xsi:type="xsd:string">2015-09-04 13:47:18</value></value></item></complex_filter></filters><pager xsi:type="ns1:pager"><page xsi:type="xsd:string">1</page><pageSize xsi:type="xsd:string">100</pageSize></pager></ns1:oroQuoteList></SOAP-ENV:Body></SOAP-ENV:Envelope>

[response]          
[code]              500


Completed
```

**Comment by rgrebenchuk** [comment]
Hi, 
Could you try latest 1.2.2 version of Oro Bridge ?

**Comment by Goeny** [comment]
How can i upgrade to 1.2.2 ?
Where do i get it?

**Comment by artml** [comment]
@Goeny it's available in [MagentoConnect](https://www.magentocommerce.com/magento-connect/orocrm-bridge.html) marketplace. The current version is 1.2.5 though.
