### ISSUE TITLE
[orocrm] Schema update Failed

### ISSUE THREAD

**Issue by dsltyyz** [orocrm/crm#130]
[oro_install.log]

[2015-08-11 17:41:32] Launching "cache:clear" command
Clearing the cache for the prod environment with debug false

Command "cache:clear" executed in 35 second(s), memory usage: 86.72Mb

[2015-08-11 17:42:12] Launching "doctrine:schema:drop" command
Dropping database schema...
Database schema dropped successfully!

Command "doctrine:schema:drop" executed in 1 second(s), memory usage: 16.41Mb

[2015-08-11 17:42:14] Launching "oro:entity-config:cache:clear" command
Clear the entity config cache

Command "oro:entity-config:cache:clear" executed in 0 second(s), memory usage: 3.00Mb

[2015-08-11 17:42:15] Launching "oro:entity-extend:cache:clear" command
Clear the extended entity cache

Command "oro:entity-extend:cache:clear" executed in 0 second(s), memory usage: 3.14Mb

[2015-08-11 17:42:17] Launching "oro:migration:load" command
Process migrations...
  > Oro\Bundle\MigrationBundle\Migration\CreateMigrationTableMigration
  > Oro\Bundle\OrganizationBundle\Migrations\Schema\OroOrganizationBundleInstaller
  > Oro\Bundle\SecurityBundle\Migrations\Schema\v1_0\OroSecurityBundle
  > Oro\Bundle\AttachmentBundle\Migrations\Schema\OroAttachmentBundleInstaller
  > Oro\Bundle\EmailBundle\Migrations\Schema\OroEmailBundleInstaller
  > Oro\Bundle\UserBundle\Migrations\Schema\OroUserBundleInstaller
  > Oro\Bundle\SSOBundle\Migrations\Schema\OroUserBundleInstaller
  > Oro\Bundle\EntityConfigBundle\Migrations\Schema\OroEntityConfigBundleInstaller
  > Oro\Bundle\EntityConfigBundle\Migrations\Schema\v1_3\OroEntityConfigBundle
  > Oro\Bundle\EntityConfigBundle\Migrations\Schema\v1_4\FixOptionSetObjects
  > Oro\Bundle\EntityConfigBundle\Migrations\Schema\v1_5\DropFieldConfig
  > Oro\Bundle\EntityExtendBundle\Migrations\Schema\OroEntityExtendBundleInstaller
  > Oro\Bundle\EntityExtendBundle\Migrations\Schema\v1_3\OroEntityExtendBundle
  > Oro\Bundle\IntegrationBundle\Migrations\Schema\OroIntegrationBundleInstaller
  > Oro\Bundle\ActivityBundle\Migrations\Schema\OroActivityBundleInstaller
  > Oro\Bundle\ActivityListBundle\Migrations\Schema\OroActivityListBundleInstaller
  > Oro\Bundle\AddressBundle\Migrations\Schema\OroAddressBundleInstaller
  > Oro\Bundle\BatchBundle\Migrations\Schema\OroBatchBundleInstaller
  > Oro\Bundle\CalendarBundle\Migrations\Schema\OroCalendarBundleInstaller
  > Oro\Bundle\CalendarBundle\Migrations\Schema\v1_9\OroCalendarBundle
  > Oro\Bundle\ConfigBundle\Migrations\Schema\OroConfigBundleInstaller
  > Oro\Bundle\CronBundle\Migrations\Schema\v1_0\OroCronBundle
  > Oro\Bundle\CronBundle\Migrations\Schema\v1_0\JmsJob
  > Oro\Bundle\CronBundle\Migrations\Schema\v1_1\JmsJob
  > Oro\Bundle\DataAuditBundle\Migrations\Schema\OroDataAuditBundleInstaller
  > Oro\Bundle\DataGridBundle\Migrations\Schema\OroDataGridBundleInstaller
  > Oro\Bundle\EmbeddedFormBundle\Migrations\Schema\OroEmbeddedFormBundleInstaller
  > Oro\Bundle\ImapBundle\Migrations\Schema\v1_0\OroImapBundle
  > Oro\Bundle\ImapBundle\Migrations\Schema\v1_1\OroImapBundle
  > Oro\Bundle\ImapBundle\Migrations\Schema\v1_2\OroImapBundle
  > Oro\Bundle\InstallerBundle\Migrations\Schema\OroInstallerBundle
  > Oro\Bundle\MigrationBundle\Migrations\Schema\v1_0\OroMigrationBundle
  > Oro\Bundle\MigrationBundle\Migrations\Schema\v1_1\OroMigrationBundle
  > Oro\Bundle\NoteBundle\Migrations\Schema\v1_0\OroNoteBundle
  > Oro\Bundle\NoteBundle\Migrations\Schema\v1_1\OroNoteBundle
  > Oro\Bundle\NotificationBundle\Migrations\Schema\OroNotificationBundleInstaller
  > Oro\Bundle\ReportBundle\Migrations\Schema\OroReportBundleInstaller
  > Oro\Bundle\SearchBundle\Migrations\Schema\OroSearchBundleInstaller
  > Oro\Bundle\SegmentBundle\Migrations\Schema\OroSegmentBundleInstaller
  > Oro\Bundle\SidebarBundle\Migrations\Schema\v1_0\OroSidebarBundle
  > Oro\Bundle\SidebarBundle\Migrations\Schema\v1_1\OroSidebarBundle
  > Oro\Bundle\TagBundle\Migrations\Schema\OroTagBundleInstaller
  > Oro\Bundle\TranslationBundle\Migrations\Schema\OroTranslationBundleInstaller
  > Oro\Bundle\WindowsBundle\Migrations\Schema\v1_0\OroWindowsBundle
  > Oro\Bundle\WorkflowBundle\Migrations\Schema\OroWorkflowBundleInstaller
  > Oro\Bundle\CommentBundle\Migrations\Schema\v1_0\OroCommentBundle
  > Oro\Bundle\DashboardBundle\Migrations\Schema\OroDashboardBundleInstaller
  > Oro\Bundle\NavigationBundle\Migrations\Schema\v1_0\OroNavigationBundle
  > Oro\Bundle\NavigationBundle\Migrations\Schema\v1_1\OroNavigationBundle
  > Oro\Bundle\NavigationBundle\Migrations\Schema\v1_2\OroNavigationBundle
  > Oro\Bundle\NavigationBundle\Migrations\Schema\v1_3\OroNavigationBundle
  > OroCRM\Bundle\ContactBundle\Migrations\Schema\OroCRMContactBundleInstaller
  > OroCRM\Bundle\AccountBundle\Migrations\Schema\OroCRMAccountBundleInstaller
  > OroCRM\Bundle\MarketingListBundle\Migrations\Schema\OroCRMMarketingListBundleInstaller
  > OroCRM\Bundle\MarketingListBundle\Migrations\Schema\v1_2\OroCRMMarketingListBundle
  > Oro\Bundle\TrackingBundle\Migrations\Schema\OroTrackingBundleInstaller
  > Oro\Bundle\ReminderBundle\Migrations\Schema\OroReminderBundleBundleInstaller
  > OroCRM\Bundle\CallBundle\Migrations\Schema\OroCRMCallBundleInstaller
  > OroCRM\Bundle\CampaignBundle\Migrations\Schema\OroCRMCampaignBundleInstaller
  > OroCRM\Bundle\ChannelBundle\Migrations\Schema\OroCRMChannelBundleInstaller
  > OroCRM\Bundle\ChannelBundle\Migrations\Schema\v1_4\OroCRMChannelBundle
  > OroCRM\Bundle\TaskBundle\Migrations\Schema\OroCRMTaskBundleInstaller
  > OroCRM\Bundle\AnalyticsBundle\Migrations\Schema\v1_0\OroCRMAnalyticsBundle
  > OroCRM\Bundle\SalesBundle\Migrations\Schema\OroCRMSalesBundleInstaller
  > OroCRM\Bundle\ContactUsBundle\Migrations\Schema\OroCRMContactUsBundleInstaller
  > OroCRM\Bundle\MagentoBundle\Migrations\Schema\OroCRMMagentoBundleInstaller
  > OroCRM\Bundle\CaseBundle\Migrations\Schema\OroCRMCaseBundleInstaller
  > OroCRM\Bundle\CaseBundle\Migrations\Schema\v1_4\OroCRMCaseBundle
  > Oro\Bundle\MigrationBundle\Migration\UpdateBundleVersionMigration
  > Oro\Bundle\EntityExtendBundle\Migration\RefreshExtendCacheMigration
    Tue Aug 11 17:44:59 2015 (5684): Fatal Error Unable to reattach to base address

    ERROR: The command terminated with an exit code: 4294967294.
  > Oro\Bundle\EntityConfigBundle\Migration\UpdateEntityConfigMigration - skipped
  > Oro\Bundle\EntityExtendBundle\Migration\UpdateExtendConfigMigration - skipped
  > Oro\Bundle\ActivityListBundle\Migration\ActivityListMigration - skipped
  > Oro\Bundle\EntityExtendBundle\Migration\UpdateExtendIndicesMigration - skipped

                                                                               
  [RuntimeException]                                                           
  Failed migrations: Oro\Bundle\EntityExtendBundle\Migration\RefreshExtendCac  
  heMigration.                                                                 
                                                                               

oro:migration:load [--force] [--dry-run] [--show-queries] [--bundles[="..."]] [--exclude[="..."]] [--timeout[="..."]] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-s|--shell] [--process-isolation] [-e|--env="..."] [--no-debug] [--current-user="..."] [--current-organization="..."] [--disabled-listeners="..."] command

Command "oro:migration:load" executed in 162 second(s), memory usage: 35.80Mb

[prod.log]
[2015-08-11 17:42:17] request.INFO: Matched route "sylius_flow_display" (parameters: "_controller": "sylius.controller.process:displayAction", "scenarioAlias": "oro_installer", "stepName": "schema", "_route": "sylius_flow_display") [] []
[2015-08-11 17:42:17] security.DEBUG: Invoked controller "Sylius\Bundle\FlowBundle\Controller\ProcessController::displayAction". (MASTER_REQUEST) [] []
[2015-08-11 17:44:59] request.CRITICAL: Uncaught PHP Exception RuntimeException: "The command terminated with an exit code: 1." at D:\server\crm-application\vendor\oro\platform\src\Oro\Bundle\InstallerBundle\CommandExecutor.php line 168 {"exception":"[object] (RuntimeException: The command terminated with an exit code: 1. at D:\\server\\crm-application\\vendor\\oro\\platform\\src\\Oro\\Bundle\\InstallerBundle\\CommandExecutor.php:168)"} []
[2015-08-11 17:44:59] security.DEBUG: Invoked controller "FOS\RestBundle\Controller\ExceptionController::showAction". (SUB_REQUEST) [] []

please someone provide an idea?

**Comment by dsltyyz** [comment]
![Uploading QQ图片20150811182302.png…]()

**Comment by dsltyyz** [comment]
![qq 20150811182503](https://cloud.githubusercontent.com/assets/9079696/9195670/32ab2e34-4057-11e5-9f7e-4c5bfcc8704d.png)

**Comment by dsltyyz** [comment]
![qq 20150811182302](https://cloud.githubusercontent.com/assets/9079696/9195672/3dbcb950-4057-11e5-9d9e-b4474df8db95.png)

**Comment by sergeyz** [comment]
Hi, @dsltyyz !

Please specify php version you use. Please disable opcache and try once again

**Comment by dsltyyz** [comment]
hi,@sergeyz
php version 5.5.28

**Comment by dsltyyz** [comment]
hi,@sergeyz
thanks for you, it is sure that opcache have some problem of settings
