### ISSUE TITLE
Lack of the "cascade" definition for the "accounts" property of the "OroCRM\Bundle\ContactBundle\Entity\Contact" entity

### ISSUE THREAD

**Issue by mikemirten** [orocrm/crm#133]
I'm not sure it's supposed to be, but the `accounts` property of the `OroCRM\Bundle\ContactBundle\Entity\Contact` entity has no `cascade` definition. It prevents to create the accounts for the imported contacts inside the strategy at once by causing the error: "**A new entity was found through the relationship 'OroCRM\Bundle\ContactBundle\Entity\Contact#accounts' that was not configured to cascade persist operations for entity...**"

I know about the process.yml config, but i don't like the idea of "Coding in the config". I've implemented all the logic in the strategy.

It would be nice to have such an opportunity "from the box".
`cascade={"all"}` for the `@ORM\ManyToMany` definition allows to create the account along with the contact.

The same situation with `OroCRM\Bundle\ContactBundle\Entity\Contact#source` if you are trying to provide a source for the contact.

**Comment by artml** [comment]
@mikemirten sounds reasonable. Can you provide a PR for our team to review? Thank you.

**Comment by mkudelya** [comment]
Hi @mikemirten 

I have tested your use case but I found no issues with contact import (I am using version 1.10.16). Could you please let me know whether you are still experiencing problems with import? Thank you.

**Comment by sadortun** [comment]
Related to #216 ?

**Comment by mikemirten** [comment]
Hi guys, it was long time ago when i've been working with the project, don't have a deployed instance anymore so cannot help you unfortunately.

**Comment by mkudelya** [comment]
@sadortun, 

Yes, it is most likely related to #216. I have updated the related issue and I am closing the current one.
