### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by GaneshKandu** [orocrm/crm#141]
Hi I am Trying to install OroCRM
getting error on &lt;domain&gt;/web/app.php/installer
in ammps

<b>Fatal error:</b> Uncaught exception 'Symfony\Component\HttpFoundation\File\Exception\FileNotFoundException' with message 'The file "The PHP executable could not be found." does not exist' in &lt;webroot&gt;\vendor\oro\platform\src\Oro\Bundle\InstallerBundle\CommandExecutor.php:322 Stack trace: #0 &lt;webroot&gt;\vendor\oro\platform\src\Oro\Bundle\EntityExtendBundle\OroEntityExtendBundle.php(172): Oro\Bundle\InstallerBundle\CommandExecutor::getPhpExecutable() #1 &lt;webroot&gt;\vendor\oro\platform\src\Oro\Bundle\EntityExtendBundle\OroEntityExtendBundle.php(97): Oro\Bundle\EntityExtendBundle\OroEntityExtendBundle-&gt;getPhpExecutable() #2 &lt;webroot&gt;\vendor\oro\platform\src\Oro\Bundle\EntityExtendBundle\OroEntityExtendBundle.php(84): Oro\Bundle\EntityExtendBundle\OroEntityExtendBundle-&gt;checkConfigs() #3 &lt;webroot&gt;\vendor\oro\platform\src\Oro\Bundle\EntityExtendBundle\OroEntityExtendBundle.php(62): Oro\Bundle\EntityExtendBundle\OroEntityEx in <b>&lt;webroot&gt;\vendor\oro\platform\src\Oro\Bundle\InstallerBundle\CommandExecutor.php</b> on line <b>322</b>

downloaded from <a href="http://www.orocrm.com/downloads/platform-application.tar.gz" >http://www.orocrm.com/downloads/platform-application.tar.gz</a> link

**Comment by sergeyz** [comment]
Hi, @GaneshKandu !

Please add php from `ammps` package to your PATH environment variable

**Comment by GaneshKandu** [comment]
hi i am added a path to environment variable and it works
but still getting an error
<br />
<b>Fatal error</b>:  Uncaught exception 'PDOException' with message 'SQLSTATE[28000] [1045] Access denied for user '&lt;db_user&gt;'@'localhost' (using password: NO)' in <public_html>/orocrm/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43
Stack trace:
#0 &lt;public_html&gt;/orocrm/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(43): PDO-&gt;__construct('mysql:host=127....', '&lt;db_user&gt;', NULL, Array)
#1 &lt;public_html&gt;/orocrm/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOMySql/Driver.php(45): Doctrine\DBAL\Driver\PDOConnection-&gt;__construct('mysql:host=127....', '&lt;db_user&gt;', NULL, Array)
#2 &lt;public_html&gt;/orocrm/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(360): Doctrine\DBAL\Driver\PDOMySql\Driver-&gt;connect(Array, '&lt;db_user&gt;', NULL, Array)
#3 &lt;public_html&gt;/orocrm/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(429): Doctrine\DBAL\Connection-&gt;connect()
#4 &lt;public_html&gt;/orocrm/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connectio in <b>&lt;public_html&gt;/orocrm/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php</b> on line <b>103</b><br />

my app/config/parameters.yml

is

parameters:
    database_driver: mysql
    database_host: &lt;host&gt;
    database_port: ~
    database_name: &lt;db name&gt;
    database_user: &lt;db user&gt;
    database_password: &lt;db password&gt;

using same parameter myphpadmin connect successfully 
Server version: 5.5.45

**Comment by sergeyz** [comment]
> `using password: NO`

please check your password not empty

**Comment by cronk1986** [comment]
Hello , I have the same problem as I fix on a CentOS server, any idea?

The error is as follows:

Fatal error: Uncaught exception 'Symfony\Component\HttpFoundation\File\Exception\FileNotFoundException' with message 'The file "The PHP executable could not be found." does not exist' in /var/www/vhosts/iterdigital.com/crm.iterdigital.com/crm-application/vendor/oro/platform/src/Oro/Bundle/InstallerBundle/CommandExecutor.php:322 Stack trace: #0 /var/www/vhosts/iterdigital.com/crm.iterdigital.com/crm-application/vendor/oro/platform/src/Oro/Bundle/EntityExtendBundle/OroEntityExtendBundle.php(172): Oro\Bundle\InstallerBundle\CommandExecutor::getPhpExecutable() #1 /var/www/vhosts/iterdigital.com/crm.iterdigital.com/crm-application/vendor/oro/platform/src/Oro/Bundle/EntityExtendBundle/OroEntityExtendBundle.php(97): Oro\Bundle\EntityExtendBundle\OroEntityExtendBundle->getPhpExecutable() #2 /var/www/vhosts/iterdigital.com/crm.iterdigital.com/crm-application/vendor/oro/platform/src/Oro/Bundle/EntityExtendBundle/OroEntityExtendBundle.php(84): Oro\Bundle\EntityExtendBundle\OroEntityExtendBundle->checkConfigs() #3 /var/www/vhosts/ite in /var/www/vhosts/iterdigital.com/crm.iterdigital.com/crm-application/vendor/oro/platform/src/Oro/Bundle/InstallerBundle/CommandExecutor.php on line 322

thank you

**Comment by rgrebenchuk** [comment]
Hi, @cronk1986 
Please check PHP CLI path added to PATH variable. Also you can define ORO_PHP_PATH environment variable with full path to php binary file

**Comment by GaneshKandu** [comment]
export ORO_PHP_PATH = <php path >/bin  ???

**Comment by cronk1986** [comment]
Hi thanks for answering , I do the following "export ORO_PHP_PATH = / usr / local / php563 -cgi / bin " and out of ssh, then when I get back into the environment variable has no value when printed as follows "echo $ ORO_PHP_PATH "

any ideas ?

thanks!

**Comment by artml** [comment]
@cronk1986 do you still experience this issue?

**Comment by GaneshKandu** [comment]
i think if "php -v" is printing same think is enough 
```
PHP 5.5.31 (cli) (built: Jan 19 2016 18:20:01)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies
    with the ionCube PHP Loader + Intrusion Protection from ioncube24.com (disabled) v5.0.7, Copyright (c) 2002-2015, by ionCube Ltd.
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
```

**Comment by GaneshKandu** [comment]
which directories are should writable to install OroCRM Application ???

**Comment by sergeyz** [comment]
Hi, @GaneshKandu!

Like any other Symfony application - app/cache and app/logs, see http://symfony.com/doc/2.7/book/installation.html#checking-symfony-application-configuration-and-setup for more details

**Comment by GaneshKandu** [comment]
thanks :+1:  I'll let you know if any problem occurs

**Comment by artml** [comment]
Since the problem appears to be fixed, I will close this issue for now. @GaneshKandu feel free to reopen it or open a new one if any problem occurs. (I hope it will not!)
