### ISSUE TITLE
Problems with magento wsdl validatation

### ISSUE THREAD

**Issue by Valentyn-Kubrak** [orocrm/crm#144]
Hello,
Can you please help with some problems. I want to integrate magento and OroCRM via
https://www.magentocommerce.com/magento-connect/orocrm-bridge.html
I installed extension, then in next step I want to create channel and in General settings credentials from magento wsdl url, api user, api key.
And I faced with problem during validation of SOAP connection:
1) Curl request making wrong validation of ssl certificate:
app.CRITICAL: MageCheck error: 0: [curl] 60: SSL certificate problem: self signed certificate [url]
Ok, I was need fast solution, so I just added somewhere “false” option for ssl validation
in guzzle/guzzle/src/Guzzle
2) Then I faced with new problem looks like Oro not waiting some time (may be timeout problem)
It returns app.CRITICAL: MageCheck error: 0: Client error response [status code] 404 [reason phrase] Not Found [url] https://magento.domain/api/v2_soap/?wsdl=1%2F
why this happens?
it should at least wait 60 seconds, because wsdl not cached
And questions – where I can control SSL validation option and timeout.
Here
\OroCRM\Bundle\MagentoBundle\Controller\SoapController::checkAction
I can see
ini_get(‘default_socket_timeout’);
it equals 60 seconds.
Please help.

**Comment by mbessolov** [comment]
Hi Valentyn,

It doesn't look like a timeout issue. According to the error you posted Oro is actually receiving a response from the server - the server responds with 404:
```
It returns app.CRITICAL: MageCheck error: 0: Client error response [status code] 404 [reason phrase] Not Found [url] https://magento.domain/api/v2_soap/?wsdl=1%2F
```
Please check your webserver configuration (rewrite rules?)

**Comment by Valentyn-Kubrak** [comment]
@mbessolov ,
Thank you for answer, 
but it works gut with curl request from console,
can you please also do you have any configurations in configs or admin interface for disabling SSL validation of url?
