### ISSUE TITLE
Why sync with oro working by some parts

### ISSUE THREAD

**Issue by Valentyn-Kubrak** [orocrm/crm#145]
I enabled syn with ORO CRM, but all customer not synced, in every attempt it taking some small amount and pulling to ORO CRM. For example my output of integration sync:

Run sync for "All Websites Integration" integration.
Start processing "website_dictionary" connector
Stats: read [3], processed [3], updated [3], added [0], deleted [0], invalid entities: [0]
Start processing "store_dictionary" connector
Stats: read [12], processed [12], updated [12], added [0], deleted [0], invalid entities: [0]
Start processing "customer_group_dictionary" connector
Stats: read [17], processed [17], updated [17], added [0], deleted [0], invalid entities: [0]
Start processing "region_dictionary" connector
Regions are up to date, last sync date is Thu, 14 Jan 2016 20:46:37 +0000, interval is 1 day
Stats: read [0], processed [0], updated [0], added [0], deleted [0], invalid entities: [0]
Start processing "customer" connector
Looking for batch
found 2 entities
Loading Customer by id: 1
Loading Customer by id: 1027
Stats: read [2], processed [2], updated [1], added [1], deleted [0], invalid entities: [0]
Start processing "cart" connector
Looking for batch
found 2 entities
Loading Cart by id: 710
Loading Cart by id: 716
Stats: read [2], processed [2], updated [1], added [1], deleted [0], invalid entities: [0]
Start processing "order" connector
Looking for batch
found 1 entities
Loading Order by id: 3282
Stats: read [1], processed [1], updated [1], added [0], deleted [0], invalid entities: [0]
Start processing "newsletter_subscriber" connector
Looking for batch
found 12 entities
Loading NewsletterSubscriber by id: 993
Loading NewsletterSubscriber by id: 815
Loading NewsletterSubscriber by id: 811
Loading NewsletterSubscriber by id: 701
Loading NewsletterSubscriber by id: 507
Loading NewsletterSubscriber by id: 408
Loading NewsletterSubscriber by id: 382
Loading NewsletterSubscriber by id: 349
Loading NewsletterSubscriber by id: 320
Loading NewsletterSubscriber by id: 236
Loading NewsletterSubscriber by id: 128
Loading NewsletterSubscriber by id: 34
Stats: read [12], processed [12], updated [12], added [0], deleted [0], invalid entities: [0]
Completed

Why only 12 entities?

**Comment by DimaSoroka** [comment]
Please check you sync start date value and check how many customers you have created after this date.

**Comment by Valentyn-Kubrak** [comment]
@DimaSoroka , thank you very much for very quick answer.
Yes, after changing this data, in sync queues new customer appeared. 
(I thought that this is start time of sync jobs execution :))
