### ISSUE TITLE
Method Oro\Bundle\InstallerBundle\Composer\ScriptHandler::setAssetsVersion is not callable, can not call post-install-cmd script

### ISSUE THREAD

**Issue by woei66** [orocrm/crm#146]
here are my steps to install oro crm
git clone https://github.com/orocrm/crm-application.git
composer install --prefer-dist --no-dev

then, everything looks fine but I saw a error message below
![2016-01-27 19_42_07](https://cloud.githubusercontent.com/assets/5770807/12612484/1908b6fc-c52e-11e5-9afe-0742e96d88c5.png)

I had read the official document and it suggested that we should use
git clone -b 1.8.2 https://github.com/orocrm/crm-application.git
to install oro-crm but I faced php memory exhausted problems when I executed
php app/console oro:install --env prod --timeout=0

I already used 1G in php.ini and it always display the error.
I have reinstalled the oro-crm several times with different approaches but none is workable.

Does anyone have a good suggestion?
Thank you.

**Comment by woei66** [comment]
one more question: what's the difference between crm and crm-application github repo?
I can't see report bug in crm-application
I was redirected to the crm github repo when I clicked the report bug on the http://www.orocrm.com/report-a-bug page

**Comment by sergeyz** [comment]
Hi, @woei66 !

Please add more information about environment
`composer show --installed | grep oro`
`php -i | grep memory_limit`

**Comment by woei66** [comment]
good, the github is back.
---

> # composer show --installed | grep oro
> oro/crm                                  dev-master 0bae06b OroCRM
> oro/doctrine-extensions                  1.0.10             Doctrine Extensions for MySQL and PostgreSQL.
> oro/jsplumb                              1.7.6              jsPlumb provides a means for a developer to visually connect elements on their web pages.
> oro/moment-timezone                      0.3.1              Parse and display dates in any timezone
> oro/platform                             dev-master 490a61d Business Application Platform (BAP)
> 

```
# php -i | grep memory_limit
memory_limit => 1024M => 1024M
```

**Comment by sergeyz** [comment]
Ok, so you you have 1.8.2 application and dev-master for crm and platform. but versions should match

`git clone -b 1.8 https://github.com/orocrm/crm-application.git`
and `composer install` afterwards

> I already used 1G in php.ini and it always display the error.
> I have reinstalled the oro-crm several times with different approaches but none is workable.

Please post output here, we need to detect what step leads to memory errors

**Comment by woei66** [comment]
I used git clone -b 1.8 https://github.com/orocrm/crm-application.git and composer install again and it passed.
It's very strange!!
![capturfiles](https://cloud.githubusercontent.com/assets/5770807/12646462/37be0fe2-c60b-11e5-8d70-b2e7145c54ec.png)

Let me explained my previous actions for your reference:
1. git clone https://github.com/orocrm/crm-application.git
2. composer install --prefer-dist --no-dev
3. php app/console oro:install --env prod --timeout=0
   Load sample data (y/n): y ===> here, I used "y"
4. php app/console clank:server --env prod
   and memory failed.

I will prepare another new environment to reproduce the case for your trouble shooting.

**Comment by woei66** [comment]
thanks to your reply.

one question:
what's the difference between current master version and v1.8?
why we can't user current master?
Is there any special reason?
thanks

**Comment by sergeyz** [comment]
Versions are stable, master is nightly build. We do not recommend to use nightly builds on production servers. Upgrade from version to version is guaranteed. Upgrade from master to later master(without data loss) is not

**Comment by woei66** [comment]
ok, I got the "memory exhausted" message for 1.8 version when I executed the command:
php app/console oro:install --env prod --timeout=0

![2016-01-29 16_00_55](https://cloud.githubusercontent.com/assets/5770807/12670211/8c8d7224-c6a1-11e5-82e0-72ac7ca07481.png)

If I execute the command again, I will get the error message
![2016-01-29 16_03_38](https://cloud.githubusercontent.com/assets/5770807/12670293/1dc61714-c6a2-11e5-926e-1b604ddd76a1.png)

**Comment by woei66** [comment]
ok, I reproduced the case.
152MB is not enough for the command "php app/console oro:install --env prod --timeout=0"
1024MB is ok.
When you install, please make sure the memory_limit is 1024M in your php.ini file.
To fix this problem, we need to tune the command "php app/console oro:install --env prod --timeout=0" and make sure objects, class and array are released.
