### ISSUE TITLE
My sales flow B2C doesn't allow custom currency  - chart

### ISSUE THREAD

**Issue by tawfekov** [orocrm/crm#147]
its keep showing $ while the currency is not USD 
crm version : 1.8.2	

![screenshot-crm 2016-01-28 12-27-30](https://cloud.githubusercontent.com/assets/94997/12641839/a2962800-c5ba-11e5-8250-933d4aa4b444.png)

**Comment by artml** [comment]
Thanks, we will address this issue in our future releases.

**Comment by dmitrosh** [comment]
Hi, Tawfek. I checked it on the same verion (1.8.2) and couldn't reproduce this issue. After one changes the currency configuration the chart uses this currency. Please specify your conditions, i.e. what currency you set, have you any customization there etc.

**Comment by artml** [comment]
No response from author for more than a month so I assume the issue is no more.
