### ISSUE TITLE
No mapping found for field 'picture' on class 'OroCRM\Bundle\ContactBundle\Entity\Contact'

### ISSUE THREAD

**Issue by annabober** [orocrm/crm#153]
After migration from 1.9.0-RC1 to 1.9.0 I have an error.

When I try view contacts, I see error message: 
`An exception has been thrown during the rendering of a template ("No mapping found for field 'picture' on class 'OroCRM\Bundle\ContactBundle\Entity\Contact'.") in vendor/oro/platform/src/Oro/Bundle/UIBundle/Resources/views/actions/index.html.twig at line 44.`

I removed all files from app/cache directory, and did oro:migration:load --force command

I  was looking for and I don't have any mapping class for table oro_attachment_file.

**Comment by iklymenko** [comment]
Hi abober,
how did you upgrade your OroCRM project to the latest release?

Did you run next command after composer update: 
`php app/console oro:platform:update --env=prod`
Because executing oro:migration:load command is not a valid way to upgrade.

**Comment by iklymenko** [comment]
Related discussion on the forum: http://www.orocrm.com/forums/topic/no-mapping-found-for-field-picture-on-class-entitycontact

**Comment by artml** [comment]
The issue has been resolved on the forum so I'm closing it.
