### ISSUE TITLE
package installation error

### ISSUE THREAD

**Issue by pinaki030** [orocrm/crm#154]
orocrm package installation giving ajax error.

how to solve it this issue?

**Comment by sergeyz** [comment]
Hi, @pinaki030!

Please provide error message and post log contents

**Comment by pinaki030** [comment]
I am always getting Ajax error to package installation

**Comment by mbessolov** [comment]
@pinaki030 , can you please attach the screenshot or provide the exact contents of the error message?

**Comment by artml** [comment]
No response from @pinaki030 for more than 30 days so I am closing this for now. If you still experience this issue, please reopen or create a new one. Thank you!
