### ISSUE TITLE
How to change all admin routes to /admin?

### ISSUE THREAD

**Issue by VitaliyBelous** [orocrm/crm#156]
Hello,

Could you please clarify how to change route to admin panel like "/admin" , And my landing page set to the "/" route.

Thanks.

**Comment by artml** [comment]
@VitaliyBelous Please [check this forum discussion](https://www.orocrm.com/forums/topic/how-to-prefix-all-routes), it should help with your question.

If you have further questions, let's proceed on the forum. Thank you.

**Comment by sadortun** [comment]
Hi @artml I had a try a the instructions in the forum, and I  wasent either able to make it work. The best result was either that /* required authentifications, or ending up in a redirect loop.

**Comment by artml** [comment]
@sadortun that's strange. I have asked our developers to provide some instructions, let's reopen this for now.

**Comment by mkudelya** [comment]
Hi @VitaliyBelous and @sadortun 

I have just added and tested additional [steps](https://www.orocrm.com/forums/topic/how-to-prefix-all-routes) which will help. I tested on platform 1.7
