### ISSUE TITLE
WsdlManager does not work properly with gzipped responses

### ISSUE THREAD

**Issue by alsma** [orocrm/crm#157]
Hi guys, we have magento installation with enabled gzip content encoding on nginx level.
I've got error following error when trying to configure integration:
```
[2016-03-04 00:12:08] app.CRITICAL: MageCheck error: 0: SOAP-ERROR: Parsing WSDL: Couldn't load from '/var/www/orocrm/app/cache/prod/oro/wsdl.cache/ba4cf9461a13b5023d9f8d7dbd54b9dc.wsdl' : Start tag expected, '<' not found  [] []
```

After investigation I've found out that issue is related to gzipped response from server.
Here is response headers
```
< HTTP/1.1 200 OK
< Date: Thu, 03 Mar 2016 22:31:40 GMT
< Content-Type: text/xml; charset=UTF-8
< Transfer-Encoding: chunked
< Connection: keep-alive
< Vary: Accept-Encoding
< Expires: Thu, 19 Nov 1981 08:52:00 GMT
< Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
< Pragma: no-cache
< Content-Encoding: gzip
< X-XSS-Protection: 1; mode=block
< X-Frame-Options: SAMEORIGIN
< X-Content-Type-Options: nosniff
```

I tried to modify code a bit and got it work with following line
```
$response = $this->guzzleClient->get($url, ['Accept-Encoding' => 'gzip'], ['decode_content' => 'gzip'])->send();
```

**Comment by iklymenko** [comment]
Hi Alexandr,
thanks for your question, but unfortunately we were not able to reproduce this issue. Could you please provide us more clear way how we can reproduce it, so it will be much easier to find a solution.

**Comment by artml** [comment]
No response for over a month so I'm closing the issue. @alsma feel free to reopen it or open a new one if you continue to experience the problem. Thank you for reporting it!
