### ISSUE TITLE
there is no newline between file upload field in form

### ISSUE THREAD

**Issue by woei66** [orocrm/crm#160]
![capturfiles](https://cloud.githubusercontent.com/assets/5770807/14011369/ee43d316-f1d8-11e5-851b-6a7635f4a252.png)

See the attached screenshot and you can see that the label string "Please Select The Region Of Report" displays at a wrong position.

my source code is written below 
`		$builder
        ->add('reportType', 'choice', array(
            'choices' => $this->arr_report,
            'choices_as_values' => true,
            'label' => 'Please select type of report'
            ))
        ->add('reportFile', 'file', array(
            'required' => true,
            'label' => 'Select the excel file'
            ))
        ->add('region', 'choice', array(
            'choices' => $this->arr_region,
            'choices_as_values' => true,
            'required' => true,
            'label' => 'Please select the region of report'
            ))`

and the twig template file is below
`{% extends "OroUIBundle:Default:index.html.twig" %}

{% block content %}

{{ form_start(form) }}
{{ form_widget(form) }}
{{ form_end(form) }}

{% endblock content %}`

**Comment by sergeyz** [comment]
Hi, @woei66! {{ form_widget(form) }} outputs fields only, try to use form_row instead

**Comment by woei66** [comment]
Hi @sergeyz 

The following codes not work.
`{% extends "OroUIBundle:Default:index.html.twig" %}

{% block content %}

{{ form_start(form) }}

{{ form_row(form.reportType) }}
{{ form_row(form.reportFile) }}
{{ form_row(form.region) }}
{{ form_row(form.year) }}
{{ form_row(form.quarter) }}
{{ form_row(form.month) }}
{{ form_row(form.week) }}

{{ form_end(form) }}

{% endblock content %}`

It displays the same wrong front-end.
Should I add more css style to control it?
Thank you

**Comment by sergeyz** [comment]
Actually every form widget has some html with control-group class https://github.com/orocrm/platform/blob/master/src/Oro/Bundle/UIBundle/Resources/views/Form/fields.html.twig#L3-L3

I think the reason is in `{% extends "OroUIBundle:Default:index.html.twig" %}` - it doesn't contains any form theme / form styling

Use `{% extends 'OroUIBundle:actions:update.html.twig' %}` parent instead or place your form inside fieldset, like:

```
    <fieldset class="form form-horizontal">
        {{ form_start(form) }}
        {{ form_widget(form) }}
        {{ form_end(form) }}
    </fieldset>
```

**Comment by artml** [comment]
@woei66 do you still need our help with this issue, or we can close it?
