### ISSUE TITLE
filter set for DataGrid View don't loading

### ISSUE THREAD

**Issue by userz58** [orocrm/crm#162]
for example:  http://demo-b2c.orocrm.com/desktop/task
1. i create my columns list
2 .i create my filter fileds set
if save new view and switch other view - filters don't loading
all fine, when you refresh page or will go from other page

**Comment by artml** [comment]
@userz58 I wasn't able to reproduce this issue. Can you please provide more detailed STR? Thank you.

**Comment by userz58** [comment]
сейчас уже все работает.
