### ISSUE TITLE
problem on create schema

### ISSUE THREAD

**Issue by chatlovely** [orocrm/crm#163]
oro crm have problem on schema , when i was create schema get error 500

**Comment by vsoroka** [comment]
Hi @chatlovely,

could you please provide more details about the error? If it is happened during web installation you can find details in "app/logs/oro_install.log"

**Comment by artml** [comment]
No feedback from author for more than a month so I'm closing this for now. @chatlovely feel free to reopen it or create a new one if you still need our help. Thank you!
