### ISSUE TITLE
Package install problem

### ISSUE THREAD

**Issue by LivelyDesigns** [orocrm/crm#165]
We are getting the following errors. Our server Guru can not pin the problem down:

http://crm.livi.cm/install.php

Displays:

Warning: date_default_timezone_get(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in /home/livi/public_html/crm.livi.cm/app/cache/dist/prod/classes.php on line 6725

Fatal error: Uncaught exception 'RuntimeException' with message 'Failed to start the session because headers have already been sent by "/home/livi/public_html/crm.livi.cm/app/cache/dist/prod/classes.php" at line 6725.' in /home/livi/public_html/crm.livi.cm/app/cache/dist/prod/classes.php:118 Stack trace: #0 /home/livi/public_html/crm.livi.cm/app/cache/dist/prod/classes.php(192): Symfony\Component\HttpFoundation\Session\Storage\NativeSessionStorage->start() #1 /home/livi/public_html/crm.livi.cm/app/cache/dist/prod/classes.php(496): Symfony\Component\HttpFoundation\Session\Storage\NativeSessionStorage->getBag('attributes') #2 /home/livi/public_html/crm.livi.cm/vendor/symfony/symfony/src/Symfony/Component/Security/Http/Firewall/ExceptionListener.php(213): Symfony\Component\HttpFoundation\Session\Session->set('_security.main....', 'http://crm.livi...') #3 /home/livi/public_html/crm.livi.cm/vendor/symfony/symfony/src/Symfony/Component/Security/Http/Firewall/ExceptionListener.php(191): Symfony\Component\Security\Http\Firewall\E in /home/livi/public_html/crm.livi.cm/vendor/twig/twig/lib/Twig/Parser.php on line 182

Here is the System Information:

Oro Packages
Package Name	Version	License
oro/moment-timezone	0.3.1	MIT
oro/jsplumb	1.7.6	MIT GPL-2.0
oro/platform	1.8.2	MIT
oro/crm	1.8.2	OSL-3.0
oro/doctrine-extensions	1.0.11	MIT
3rd Party Packages
Package Name	Version	License
psr/log	1.0.0	MIT
twig/twig	v1.20.0	BSD-3-Clause
doctrine/lexer	v1.0.1	MIT
doctrine/annotations	v1.2.7	MIT
doctrine/collections	v1.3.0	MIT
symfony/icu	v1.2.2	MIT
sensio/generator-bundle	v2.5.3	MIT
kriswallsmith/assetic	v1.1.2	MIT
robloach/component-installer	0.2.3	MIT
components/font-awesome	4.3.0	MIT OFL-1.1
ezyang/htmlpurifier	v4.6.0	LGPL
nesbot/carbon	1.8.0	MIT
swiftmailer/swiftmailer	v5.4.1	MIT
monolog/monolog	1.8.0	MIT
doctrine/instantiator	1.0.5	MIT
doctrine/dbal	v2.5.1	MIT
doctrine/orm	v2.5.1	MIT
akeneo/batch-bundle	0.4.2	MIT
composer/composer	1.0.0-p1	MIT
sylius/flow-bundle	v0.6.0	MIT
lexik/maintenance-bundle	1.0.3	MIT
a2lix/translation-form-bundle	1.3	MIT
zendframework/zend-stdlib	2.1.5	BSD-3-Clause
zendframework/zend-servicemanager	2.1.5	BSD-3-Clause
zendframework/zend-i18n	2.1.5	BSD-3-Clause
zendframework/zend-validator	2.1.5	BSD-3-Clause
zendframework/zend-math	2.1.5	BSD-3-Clause
zendframework/zend-crypt	2.1.5	BSD-3-Clause
zendframework/zend-mime	2.1.5	BSD-3-Clause
zendframework/zend-loader	2.1.5	BSD-3-Clause
zendframework/zend-mail	2.1.5	BSD-3-Clause
genemu/form-bundle	v2.2.1	MIT
leafo/lessphp	v0.4.0	MIT GPL-3.0
escapestudios/wsse-authentication-bundle	1.0.2	MIT
behat/transliterator	v1.1.0	Artistic-1.0
gedmo/doctrine-extensions	v2.3.12	MIT
stof/doctrine-extensions-bundle	v1.1.0	MIT
ass/xmlsecurity	v1.0.0	BSD-3-Clause
besimple/soap	v0.2.2	MIT
nelmio/api-doc-bundle	2.9.0	MIT
willdurand/jsonp-callback-validator	v1.1.0	MIT
friendsofsymfony/jsrouting-bundle	1.5.4	MIT
willdurand/negotiation	1.5.0	MIT
friendsofsymfony/rest-bundle	1.7.1	MIT
knplabs/knp-menu	v2.0.0-alpha2	MIT
knplabs/knp-menu-bundle	v2.0.0-alpha2	MIT
phpoption/phpoption	1.5.0	Apache2
phpcollection/phpcollection	0.2.0	Apache2
jms/parser-lib	1.0.0	Apache2
jms/metadata	1.5.1	Apache
jms/serializer	0.14.0	Apache2
jms/serializer-bundle	0.13.0	Apache2
jms/cg	1.1.0	Apache2
jms/di-extra-bundle	1.6.0	Apache
jms/job-queue-bundle	1.2.0	Apache2
incenteev/composer-parameter-handler	v2.1.0	MIT
sensio/framework-extra-bundle	v2.3.4	MIT
sensio/distribution-bundle	v2.3.14	MIT
symfony/assetic-bundle	v2.3.0	MIT
twig/extensions	v1.0.1	MIT
doctrine/data-fixtures	v1.1.1	MIT
jdorn/sql-formatter	v1.2.17	MIT
doctrine/doctrine-bundle	v1.4.0	MIT
doctrine/doctrine-fixtures-bundle	v2.2.0	MIT
guzzle/guzzle	v3.7.4	MIT
evenement/evenement	v1.0.0	MIT
react/stream	v0.3.4	MIT
react/event-loop	v0.3.4	MIT
react/socket	v0.3.4	MIT
cboden/ratchet	v0.2.8	MIT
jdare/clank-bundle	0.1.6	MIT
symfony/monolog-bundle	v2.7.1	MIT
imagine/imagine	v0.5.0	MIT
liip/imagine-bundle	v0.17.1	MIT
mtdowling/cron-expression	v1.0.4	MIT
ocramius/proxy-manager	0.4.1	MIT
knplabs/gaufrette	v0.1.9	MIT
knplabs/knp-gaufrette-bundle	v0.1.7	MIT
rhumsaa/uuid	2.7.4	MIT
tinymce/tinymce	4.1.10	LGPL-2.1
kriswallsmith/buzz	v0.15	MIT
components/jquery	2.1.4	MIT
components/underscore	1.7.0	MIT
components/backbone	1.1.2	MIT
mustangostang/spyc	0.5.1	MIT License
doctrine/inflector	v1.1.0	MIT
doctrine/cache	v1.6.0	MIT
doctrine/common	v2.5.3	MIT
symfony/symfony	v2.7.6	MIT
hwi/oauth-bundle	0.4.0	MIT
piwik/device-detector	3.5.0	LGPL-3.0+
symfony/swiftmailer-bundle	v2.3.11	MIT
moment/moment	2.11.1	MIT
justinrainbow/json-schema	v1.6.0	BSD-3-Clause
seld/jsonlint	1.4.0	MIT
michelf/php-markdown	1.6.0	BSD-3-Clause
doctrine/doctrine-cache-bundle	1.2.2	MIT
zendframework/zend-eventmanager	3.0.0	BSD-3-Clause
zendframework/zend-code	2.6.2	BSD-3-Clause
jms/aop-bundle	1.2.0	Apache-2.0

**Comment by DimaSoroka** [comment]
Please update value of [date.timezone](http://php.net/manual/en/datetime.configuration.php#ini.date.timezone) in your php.ini configuration file.

**Comment by LivelyDesigns** [comment]
I'm baffled because, it IS set
"date.timezone=America/New_York" in php.ini

**Comment by DimaSoroka** [comment]
Maybe you have multiple php.ini files? Please check phpinfo.

**Comment by LivelyDesigns** [comment]
Thank you for the response. We did find where another programmer had added another phpinfo without our knowledge to try to improve the speed of loading. We removed that and were able to get into the installed packages area. When we tried updating the packages we recieved these errors.

CURRENT VERSION         LATEST VERSION
1.0.0-p1 (833ce98)           1.0.2 (a083aa5) 

  × composer/composer can't be updated!_Loading composer repositories with package information Updating dependencies Your requirements could not be resolved to an installable set of packages. Problem 1 - symfony/icu v1.2.2 requires lib-icu >=4.4 -> the requested linked library icu has the wrong version installed or is missing from your system, make sure to have the extension providing it. - symfony/icu v1.2.2 requires lib-icu >=4.4 -> the requested linked library icu has the wrong version installed or is missing from your system, make sure to have the extension providing it. - Installation request for symfony/icu == 1.2.2.0 -> satisfiable by symfony/icu[v1.2.2].

Now we are getting these errors when trying to log into the program:

Warning: require(/home/livi/public_html/crm.livi.cm/app/cache/prod/doctrine/orm/Proxies/__CG__OroBundleOrganizationBundleEntityBusinessUnit.php): failed to open stream: No such file or directory in /home/livi/public_html/crm.livi.cm/vendor/doctrine/common/lib/Doctrine/Common/Proxy/AbstractProxyFactory.php on line 209

Fatal error: require(): Failed opening required '/home/livi/public_html/crm.livi.cm/app/cache/prod/doctrine/orm/Proxies/__CG__OroBundleOrganizationBundleEntityBusinessUnit.php' (include_path='.:/opt/cpanel/ea-php56/root/usr/share/pear') in /home/livi/public_html/crm.livi.cm/vendor/doctrine/common/lib/Doctrine/Common/Proxy/AbstractProxyFactory.php on line 209

**Comment by itskawsar** [comment]
I am facing same problem when installing using `composer` and getting following message:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - oro/platform 1.x-dev requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - oro/platform 1.x-dev requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - Installation request for oro/platform == 1.9999999.9999999.9999999-dev -> satisfiable by oro/platform[1.x-dev].

  To enable extensions, verify that they are enabled in those .ini files:
    - /etc/php/7.0/cli/php.ini
    - /etc/php/7.0/cli/conf.d/10-mysqlnd.ini
    - /etc/php/7.0/cli/conf.d/10-opcache.ini
    - /etc/php/7.0/cli/conf.d/10-pdo.ini
    - /etc/php/7.0/cli/conf.d/15-xml.ini
    - /etc/php/7.0/cli/conf.d/20-calendar.ini
    - /etc/php/7.0/cli/conf.d/20-ctype.ini
    - /etc/php/7.0/cli/conf.d/20-dom.ini
    - /etc/php/7.0/cli/conf.d/20-exif.ini
    - /etc/php/7.0/cli/conf.d/20-fileinfo.ini
    - /etc/php/7.0/cli/conf.d/20-ftp.ini
    - /etc/php/7.0/cli/conf.d/20-gd.ini
    - /etc/php/7.0/cli/conf.d/20-gettext.ini
    - /etc/php/7.0/cli/conf.d/20-iconv.ini
    - /etc/php/7.0/cli/conf.d/20-intl.ini
    - /etc/php/7.0/cli/conf.d/20-json.ini
    - /etc/php/7.0/cli/conf.d/20-mcrypt.ini
    - /etc/php/7.0/cli/conf.d/20-mysqli.ini
    - /etc/php/7.0/cli/conf.d/20-pdo_mysql.ini
    - /etc/php/7.0/cli/conf.d/20-phar.ini
    - /etc/php/7.0/cli/conf.d/20-posix.ini
    - /etc/php/7.0/cli/conf.d/20-readline.ini
    - /etc/php/7.0/cli/conf.d/20-shmop.ini
    - /etc/php/7.0/cli/conf.d/20-simplexml.ini
    - /etc/php/7.0/cli/conf.d/20-sockets.ini
    - /etc/php/7.0/cli/conf.d/20-sysvmsg.ini
    - /etc/php/7.0/cli/conf.d/20-sysvsem.ini
    - /etc/php/7.0/cli/conf.d/20-sysvshm.ini
    - /etc/php/7.0/cli/conf.d/20-tokenizer.ini
    - /etc/php/7.0/cli/conf.d/20-wddx.ini
    - /etc/php/7.0/cli/conf.d/20-xmlreader.ini
    - /etc/php/7.0/cli/conf.d/20-xmlwriter.ini
    - /etc/php/7.0/cli/conf.d/20-xsl.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.
```
After checking i got following _ini_ in my machine when i execute `php --ini`:

```
Configuration File (php.ini) Path: /etc/php/7.0/cli
Loaded Configuration File:         /etc/php/7.0/cli/php.ini
Scan for additional .ini files in: /etc/php/7.0/cli/conf.d
Additional .ini files parsed:      /etc/php/7.0/cli/conf.d/10-mysqlnd.ini,
/etc/php/7.0/cli/conf.d/10-opcache.ini,
/etc/php/7.0/cli/conf.d/10-pdo.ini,
/etc/php/7.0/cli/conf.d/15-xml.ini,
/etc/php/7.0/cli/conf.d/20-calendar.ini,
/etc/php/7.0/cli/conf.d/20-ctype.ini,
/etc/php/7.0/cli/conf.d/20-dom.ini,
/etc/php/7.0/cli/conf.d/20-exif.ini,
/etc/php/7.0/cli/conf.d/20-fileinfo.ini,
/etc/php/7.0/cli/conf.d/20-ftp.ini,
/etc/php/7.0/cli/conf.d/20-gd.ini,
/etc/php/7.0/cli/conf.d/20-gettext.ini,
/etc/php/7.0/cli/conf.d/20-iconv.ini,
/etc/php/7.0/cli/conf.d/20-intl.ini,
/etc/php/7.0/cli/conf.d/20-json.ini,
/etc/php/7.0/cli/conf.d/20-mcrypt.ini,
/etc/php/7.0/cli/conf.d/20-mysqli.ini,
/etc/php/7.0/cli/conf.d/20-pdo_mysql.ini,
/etc/php/7.0/cli/conf.d/20-phar.ini,
/etc/php/7.0/cli/conf.d/20-posix.ini,
/etc/php/7.0/cli/conf.d/20-readline.ini,
/etc/php/7.0/cli/conf.d/20-shmop.ini,
/etc/php/7.0/cli/conf.d/20-simplexml.ini,
/etc/php/7.0/cli/conf.d/20-sockets.ini,
/etc/php/7.0/cli/conf.d/20-sysvmsg.ini,
/etc/php/7.0/cli/conf.d/20-sysvsem.ini,
/etc/php/7.0/cli/conf.d/20-sysvshm.ini,
/etc/php/7.0/cli/conf.d/20-tokenizer.ini,
/etc/php/7.0/cli/conf.d/20-wddx.ini,
/etc/php/7.0/cli/conf.d/20-xmlreader.ini,
/etc/php/7.0/cli/conf.d/20-xmlwriter.ini,
/etc/php/7.0/cli/conf.d/20-xsl.ini
```

**Comment by DimaSoroka** [comment]
Based on message you provided, you need to install mbstring extension for php

**Comment by artml** [comment]
@LivelyDesigns do you still experience this issue?

**Comment by artml** [comment]
Apparently the issue has been fixed so I'm closing this.
