### ISSUE TITLE
Database initialization - Schema update failed

### ISSUE THREAD

**Issue by achyuth** [orocrm/crm#166]
Hi All, Could you any one please help me on this error

below is install log file error message

`[2016-05-03 07:30:11] Launching "oro:migration:load" command
Process migrations...
  > Oro\Bundle\EntityExtendBundle\Migration\LoadEntityConfigStateMigration
  > Oro\Bundle\OrganizationBundle\Migrations\Schema\OroOrganizationBundleInstaller
    ERROR: The table with name 'oro_crm.oro_organization' already exists.
  > Oro\Bundle\SecurityBundle\Migrations\Schema\OroSecurityBundleInstaller - skipped
  > Oro\Bundle\AttachmentBundle\Migrations\Schema\OroAttachmentBundleInstaller - skipped
  > Oro\Bundle\EmailBundle\Migrations\Schema\OroEmailBundleInstaller - skipped
  > Oro\Bundle\CronBundle\Migrations\Schema\OroCronBundleInstaller - skipped
  > Oro\Bundle\UserBundle\Migrations\Schema\OroUserBundleInstaller - skipped
  > Oro\Bundle\SSOBundle\Migrations\Schema\OroUserBundleInstaller - skipped
  > Oro\Bundle\EntityConfigBundle\Migrations\Schema\OroEntityConfigBundleInstaller - skipped
  > Oro\Bundle\EntityExtendBundle\Migrations\Schema\OroEntityExtendBundleInstaller - skipped
  > Oro\Bundle\IntegrationBundle\Migrations\Schema\OroIntegrationBundleInstaller - skipped
  > Oro\Bundle\ActivityBundle\Migrations\Schema\OroActivityBundleInstaller - skipped
  > Oro\Bundle\ActivityListBundle\Migrations\Schema\OroActivityListBundleInstaller - skipped
  > Oro\Bundle\AddressBundle\Migrations\Schema\OroAddressBundleInstaller - skipped
  > Oro\Bundle\BatchBundle\Migrations\Schema\OroBatchBundleInstaller - skipped
  > Oro\Bundle\CalendarBundle\Migrations\Schema\OroCalendarBundleInstaller - skipped
  > Oro\Bundle\ConfigBundle\Migrations\Schema\OroConfigBundleInstaller - skipped
  > Oro\Bundle\DataAuditBundle\Migrations\Schema\OroDataAuditBundleInstaller - skipped
  > Oro\Bundle\DataGridBundle\Migrations\Schema\OroDataGridBundleInstaller - skipped
  > Oro\Bundle\EmbeddedFormBundle\Migrations\Schema\OroEmbeddedFormBundleInstaller - skipped
  > Oro\Bundle\ImapBundle\Migrations\Schema\OroImapBundleInstaller - skipped
  > Oro\Bundle\InstallerBundle\Migrations\Schema\OroInstallerBundleInstaller - skipped
  > Oro\Bundle\MigrationBundle\Migrations\Schema\OroMigrationBundleInstaller - skipped
  > Oro\Bundle\NoteBundle\Migrations\Schema\OroNoteBundleInstaller - skipped
  > Oro\Bundle\NotificationBundle\Migrations\Schema\OroNotificationBundleInstaller - skipped
  > Oro\Bundle\ReportBundle\Migrations\Schema\OroReportBundleInstaller - skipped
  > Oro\Bundle\SearchBundle\Migrations\Schema\OroSearchBundleInstaller - skipped
  > Oro\Bundle\SegmentBundle\Migrations\Schema\OroSegmentBundleInstaller - skipped
  > Oro\Bundle\SidebarBundle\Migrations\Schema\OroSidebarBundleInstaller - skipped
  > Oro\Bundle\TagBundle\Migrations\Schema\OroTagBundleInstaller - skipped
  > Oro\Bundle\TranslationBundle\Migrations\Schema\OroTranslationBundleInstaller - skipped
  > Oro\Bundle\WindowsBundle\Migrations\Schema\v1_0\OroWindowsBundle - skipped
  > Oro\Bundle\WindowsBundle\Migrations\Schema\v1_1\OroWindowsBundle - skipped
  > Oro\Bundle\WorkflowBundle\Migrations\Schema\OroWorkflowBundleInstaller - skipped
  > OroCRM\Bundle\ActivityContactBundle\Migrations\Schema\OroCRMActivityContactBundleInstaller - skipped
  > Oro\Bundle\CommentBundle\Migrations\Schema\OroCommentBundleInstaller - skipped
  > Oro\Bundle\DashboardBundle\Migrations\Schema\OroDashboardBundleInstaller - skipped
  > Oro\Bundle\NavigationBundle\Migrations\Schema\OroNavigationBundleInstaller - skipped
  > OroCRM\Bundle\ContactBundle\Migrations\Schema\OroCRMContactBundleInstaller - skipped
  > OroCRM\Bundle\AccountBundle\Migrations\Schema\OroCRMAccountBundleInstaller - skipped
  > OroCRM\Bundle\MarketingListBundle\Migrations\Schema\OroCRMMarketingListBundleInstaller - skipped
  > Oro\Bundle\TrackingBundle\Migrations\Schema\OroTrackingBundleInstaller - skipped
  > Oro\Bundle\ReminderBundle\Migrations\Schema\OroReminderBundleBundleInstaller - skipped
  > OroCRM\Bundle\CallBundle\Migrations\Schema\OroCRMCallBundleInstaller - skipped
  > OroCRM\Bundle\CampaignBundle\Migrations\Schema\OroCRMCampaignBundleInstaller - skipped
  > OroCRM\Bundle\ChannelBundle\Migrations\Schema\OroCRMChannelBundleInstaller - skipped
  > OroCRM\Bundle\TaskBundle\Migrations\Schema\OroCRMTaskBundleInstaller - skipped
  > OroCRM\Bundle\AnalyticsBundle\Migrations\Schema\OroCRMAnalyticsBundleInstaller - skipped
  > OroCRM\Bundle\SalesBundle\Migrations\Schema\OroCRMSalesBundleInstaller - skipped
  > OroCRM\Bundle\ContactUsBundle\Migrations\Schema\OroCRMContactUsBundleInstaller - skipped
  > OroCRM\Bundle\MagentoBundle\Migrations\Schema\OroCRMMagentoBundleInstaller - skipped
  > OroCRM\Bundle\CaseBundle\Migrations\Schema\OroCRMCaseBundleInstaller - skipped
  > Oro\Bundle\MigrationBundle\Migration\UpdateBundleVersionMigration
  > Oro\Bundle\EntityExtendBundle\Migration\RefreshExtendCacheMigration - skipped
  > Oro\Bundle\EntityConfigBundle\Migration\UpdateEntityConfigMigration - skipped
  > Oro\Bundle\EntityExtendBundle\Migration\UpdateExtendConfigMigration - skipped
  > OroCRM\Bundle\ActivityContactBundle\Migration\ActivityContactMigration - skipped
  > Oro\Bundle\ActivityListBundle\Migration\ActivityListMigration - skipped
  > Oro\Bundle\EntityExtendBundle\Migration\UpdateExtendIndicesMigration - skipped
  > Oro\Bundle\EntityConfigBundle\Migration\WarmUpEntityConfigCacheMigration - skipped

                                                                               
  [RuntimeException]                                                           
  Failed migrations: Oro\Bundle\OrganizationBundle\Migrations\Schema\OroOrgan  
  izationBundleInstaller.                                                      
                                                                               

oro:migration:load [--force] [--dry-run] [--show-queries] [--bundles [BUNDLES]] [--exclude [EXCLUDE]] [--timeout [TIMEOUT]] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-s|--shell] [--process-isolation] [-e|--env ENV] [--no-debug] [--disabled-listeners DISABLED-LISTENERS] [--] <command>

Command "oro:migration:load" executed in 6 second(s), memory usage: 16.23Mb`

**Comment by iklymenko** [comment]
Hi @achyuth, 
as I understood you this is peace of the install.log. If yes - please clear the database (or drop it and create again) and try to install the application again.

**Comment by artml** [comment]
@achyuth do you still experience this issue, or it has been fixed?

**Comment by achyuth** [comment]
Sorry for to updated this issue.

I was cleared this issue by using oro:platform:update command.
And to perform complete reinstall oro:install with --force option
