### ISSUE TITLE
Restored custom field (previously deleted) not showing up

### ISSUE THREAD

**Issue by eldonbite** [orocrm/crm#168]
Hi,

I deleted a custom field from the Contact entity, then later on restored it. However it does not show up in the Contacts grid, nor in the form even after restoring it. Any idea what caused this? Or do I need to run a console command or something?

![image](https://cloud.githubusercontent.com/assets/3441674/15005864/74ba6d86-11fc-11e6-887b-1fea9a3b8ee6.png)

![image](https://cloud.githubusercontent.com/assets/3441674/15005824/1913fb3c-11fc-11e6-8b97-ff323cd5fe73.png)

![image](https://cloud.githubusercontent.com/assets/3441674/15005890/bd0c9a50-11fc-11e6-9af4-d9c37b52ab00.png)

Thanks!

**Comment by eldonbite** [comment]
BTW I am using OroCRM v1.9.3.

**Comment by rudenskij** [comment]
Hi Eldonbite ,

Thank you for submitting your request. We will investigate this issue and fix it in a future update of OroCRM. We look forward to assisting you!

Thank you,
Alex

**Comment by artml** [comment]
This has been fixed in 1.9 branch back in May. Closing this for now; @eldonbite feel free to reopen if the issue reappears. Thank you!
