### ISSUE TITLE
Color Picker and Default values

### ISSUE THREAD

**Issue by sadortun** [orocrm/crm#169]
Hi,

There is a small UI bug :
How to reproduce : 
1) Uncheck Use Defaults
![image](https://cloud.githubusercontent.com/assets/794449/15061498/451b13ce-1304-11e6-9247-39bd78534ba5.png)

2) Click on a color, TWICE
![image](https://cloud.githubusercontent.com/assets/794449/15061508/505e5336-1304-11e6-91ac-81f7b58b22c6.png)

3) Check Use Defaults
![image](https://cloud.githubusercontent.com/assets/794449/15061532/91f275f2-1304-11e6-8965-8a3d4055294e.png)

Expected : The picker popup closes.
Actual : Picker popup remain open, and cannot be close when pressing `Close`

**Comment by Grygir** [comment]
Hello @sadortun,

Thank you for the report. We've added this issue to our backlog.

**Comment by Grygir** [comment]
Hello @sadortun.
What OroCRM version do you use? It looks like it is not an issue any more for latest version http://demo.orocrm.com/desktop/config/system/platform/look_and_feel

**Comment by rudenskij** [comment]
Hi Sadortun,

Thank you for submitting your request. Actually, there is a small UI bug that you have described above. We will fix it in a future update of OroCRM.

Thank you,
Alex

**Comment by artml** [comment]
@sadortun the fix is already in the current master branch and will be shipped within 1.10 stable version.

Thanks for making us better!
