### ISSUE TITLE
Call duration field should allow more input formats

### ISSUE THREAD

**Issue by sadortun** [orocrm/crm#171]
Hi !

Currently the duration field seems only to accept the format `hh:mm:ss` which is not intuitive when entering times.

I would recommend that the following formats to be supported
- integer  ex: `42` that is converted to minutes
- string  ex `1h15` 

Thanks,
Samuel

**Comment by artml** [comment]
@sadortun we are going to add the latter option in the upcoming release. The feature should be in master soon.
