### ISSUE TITLE
Creating a task due "today" should set the time correctly

### ISSUE THREAD

**Issue by sadortun** [orocrm/crm#173]
Hi,

When creating a task due today, the  `Due date must not be in the past`

1. Create a task
2. Click on date field
3. Click Today
4. Save

Result : Error message  `Due date must not be in the past`

Expected : 
- Task is created with no time ;or
-  with time at 23:59
- With date =  tomorow 0h00

![image](https://cloud.githubusercontent.com/assets/794449/15623103/37e96bec-243e-11e6-8f45-bd4224553a8d.png)

![image](https://cloud.githubusercontent.com/assets/794449/15623113/4d34b8da-243e-11e6-934d-3f2469a2cc94.png)

**Comment by Grygir** [comment]
Hi @sadortun, 

Thank you for reporting the issue. We're going to fix it in coming release.

**Comment by artml** [comment]
@sadortun added this to scope of 1.10 release, should be fixed soon.
