### ISSUE TITLE
Tasks "Assign to" does not escape special chars correctly

### ISSUE THREAD

**Issue by sadortun** [orocrm/crm#174]
Hi,

My last name contains a `'` and is replaced by the html entity in the `Assign to` field in the tasks

![image](https://cloud.githubusercontent.com/assets/794449/15623384/dc2bef0c-2440-11e6-9196-25f94fb642cc.png)

This issue also affect `Contacts` -> `Assign to` field

**Comment by Grygir** [comment]
Hi @sadortun,

Thank you for reporting the issue. We will fix it.

**Comment by artml** [comment]
@sadortun this has already been fixed and pushed to the master branch; will be released within 1.10 stable version. Thanks for reporting this bug!
