### ISSUE TITLE
Oro installation

### ISSUE THREAD

**Issue by RodolVelasco** [orocrm/crm#175]
Im using public c9 workspace installation in order to install oro crm. Have you ever tried to use this enviroments?

I had a problem with app/cache with some encript message or something like that and to solve it I comment lines in OroRequirements.php.

Right now I had a problem with Load Sample Data in Step 4. After it failed It misses the next steps

**Comment by DimaSoroka** [comment]
We didn't try c9 at oro, what is your environment, web server and PHP configuration?

**Comment by vfbsilva** [comment]
Check the memory usage on the moment composer is running. I had to modify my php.ini to accommodate it.

**Comment by RodolVelasco** [comment]
Im gonna close this because at the end I could install oro succesfully in c9
