### ISSUE TITLE
Recent emails not clickable

### ISSUE THREAD

**Issue by sadortun** [orocrm/crm#177]
Hi Oro Team,

On the Recent Emails dashboard widget,  the emails row's are not clickable, therefore, to view the email we need to click on `View All` or go in the  `My  emails`. It would be nice to be able to use the dashboard widget to go directly to the email.

![image](https://cloud.githubusercontent.com/assets/794449/15696860/9094ba2a-2782-11e6-8b95-00438c919e6f.png)

**Comment by Grygir** [comment]
Hi @sadortun,

Thank you for reporting the issue. We are planning to improve UX for Resent Emails on dashboard. It'll be done in one of coming releases.

**Comment by mkudelya** [comment]
Hi @sadortun 

The issue has already been fixed in version 2.1.
Thank you!
