### ISSUE TITLE
Running install a second time results in a blank screen

### ISSUE THREAD

**Issue by vfbsilva** [orocrm/crm#178]
I'm using oroCRM 1.9.0 and stumbled into situation where when I drop the database and try to run install a second time I step into a blank screen on the installation step 3. The issue is fixed by setting the time stamp on the  "installed" field in app/config/parameters.yml.

Steps to reproduce:
1. Install oroCRM
2. Drop database
3. Try to install it from same install folder.

Expected: New installation.

Occurs: blank screen at page 3.

**Comment by sadortun** [comment]
Did you clear the cache?

**Comment by vfbsilva** [comment]
Yes I did. I've followed this: https://www.mavenecommerce.com/oro-book/orocrm-reset-installation/

**Comment by startupz** [comment]
Do you have APC cache enabled?

Maybe you should do this :

1. Remove cache folder (app/cache)
1. Remove APC cache
1. Force new install

We had some issues with APC cache on new install (after upgrade or simple new install)

**Comment by mkudelya** [comment]
You can:

- clear cache
- drop and create database
- run "php app/console oro:install --env prod" command in project directory

In console you at least will see probable errors.

**Comment by vfbsilva** [comment]
Removing the folder did make the trick.Thanks @startupz   @mkudelya you are right command line gave me the errors in place.

**Comment by artml** [comment]
@vfbsilva can we close this issue if your problem has been solved?

**Comment by vfbsilva** [comment]
Yes you can close it. Thanks for the support.

Em ter, 14 de jun de 2016 15:04, Artem Liubeznyi <notifications@github.com>
escreveu:
