### ISSUE TITLE
Business customer, Contact and Opportunities

### ISSUE THREAD

**Issue by sadortun** [orocrm/crm#179]
Hi OroTeam,

To simplify the contact creation process, when creating an Opportunity or a Business customer

When creating both of the  Account and Contact in the form :
![image](https://cloud.githubusercontent.com/assets/794449/15981480/1d623504-2f44-11e6-95ef-cc455092cd3e.png)

The Created contact should be assigned to the account.

This would save a step and be less error-prone

Thanks,
Samuel

**Comment by artml** [comment]
@sadortun makes perfect sense, thank you for the suggestion! I will include this into the scope of our 1.10 release.

**Comment by Rodske** [comment]
Any idea on a 1.10 launch date?

**Comment by sadortun** [comment]
@Rodske  June 30   https://github.com/orocrm/crm/milestones

**Comment by artml** [comment]
@Rodske please take into account that it's our target date; unexpected delays still might happen. We will do our best to avoid them though :)

**Comment by Rodske** [comment]
@artml, I totally appreciate that. It's a ballpark, but it really handy to know for how we set expectations with our clients. It's much better than; "We have no idea, hopefully sometime this year. Maybe before Q4." So, thanks for giving us an indication.
