### ISSUE TITLE
Customer Contact Mass Import Bug

### ISSUE THREAD

**Issue by LiamToohey** [orocrm/crm#181]
When conducting a mass import of contacts, I am seeing an issue with the custom tags. I intend to display a single custom tag (either 'b2b' or 'b2c') for a contact, however it appears to be showing multiple times within the admin grid. Below is the custom tag field within my import csv and the end result after a mass import. 

*Column in csv:*
![image](https://cloud.githubusercontent.com/assets/10517851/16108735/e8c3645a-339c-11e6-8d52-301274ea9232.png)

*Result in grid post import:*
![image](https://cloud.githubusercontent.com/assets/10517851/16108718/c63305a8-339c-11e6-8f0d-7aa92a39f7ba.png)

Any idea on what is causing this issue or how to resolve?

**Comment by artml** [comment]
@LiamToohey thanks for reporting this issue. We will investigate it and get back to you soon.

Can you tell us which version of OroCRM do you use? Thank you.

**Comment by rudenskij** [comment]
@LiamToohey, we have fixed this issue. Please be patient while waiting for the next release of OroCRM.

Thank you
Alex

**Comment by Rodske** [comment]
Any indication of how far away 1.10 will be?

**Comment by artml** [comment]
@Rodske pretty soon. We want it shipped in July.
