### ISSUE TITLE
Opportunities sorting by 'Status' field don't work.

### ISSUE THREAD

**Issue by glutaminefree** [orocrm/crm#182]
After click at 'status' in table header, list reloaded, but it real sorting not changed.
And sorting arrows appears on two fields at same time.

**Comment by artml** [comment]
@glutaminefree please tell us which version you are using. Thanks!

**Comment by glutaminefree** [comment]
![oro](https://cloud.githubusercontent.com/assets/2122419/16375176/342d68ba-3c6b-11e6-8d36-dc8209a90282.png)

**Comment by artml** [comment]
@glutaminefree I am trying to reproduce it on our current dev master but the sorting works just fine.

What happens if you reload the page?

**Comment by glutaminefree** [comment]
@artml, items sorted by 'Created at' field. If you can't reproduce it, I'll try it with clean install. But later.

**Comment by artml** [comment]
@glutaminefree ok, please let us know if you still experience the issue. Thank you!

**Comment by glutaminefree** [comment]
@artml, hi!

I install OroCrm today, using [this](https://www.orocrm.com/documentation/index/current/book/installation) guide (last version from master branch). I install sample data too.
Opportunities still doesn't sorting.

![oro-no-sorting](https://cloud.githubusercontent.com/assets/2122419/16445728/1d54e3d0-3df5-11e6-975d-2748c5418173.png)

My env:
Fedora 23 x86_64 with latest updates.
HTTPD 2.4.18
PHP 5.6.22
MariaDB 10.0.23

**Comment by amuzalevskiy** [comment]
Hi @glutaminefree 

I tried to reproduce your issue, but sorting in my environment is working as expected. Checked all the frontend code which works during sort request and didn't see any place which can cause issue you described.

Have you got any javascript errors during your tests?
Does the test result depend on browser(I used chrome for tests)?
Could you please provide URL requested after you initiate sorting? ( This short video shows how to find it https://drive.google.com/file/d/0B7Lq01V_dOIJblJRTElOQ3FMakE/view in chrome)

Thanks for you report

**Comment by glutaminefree** [comment]
Steps:

1. Open page /opportunity
2. Click on 'Status' label in table head.
3. Items list on page reloaded via AJAX, but URL has not changed (still /opportunity)

In FF 47 and Chrome 51 all the same.


Hmmm. App send AJAX request to URL
`/datagrid/sales-opportunity-grid?sales-opportunity-grid[_pager][_page]=1&sales-opportunity-grid[_pager][_per_page]=25&sales-opportunity-grid[_parameters][view]=__all__&sales-opportunity-grid[_sort_by][status]=ASC`
and it return 500 status.
I'm going to see the error logs.

**Comment by glutaminefree** [comment]
From /app/logs/prod.log:

`request.CRITICAL: Uncaught PHP Exception Doctrine\ORM\Query\QueryException: "[Semantical Error] line 0, col 1086 near 'status.id AS': Error: 'status' does not point to a Class." at /var/www/html/oro-clean.loc/vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php line 63 {"exception":"[object] (Doctrine\\ORM\\Query\\QueryException: [Semantical Error] line 0, col 1086 near 'status.id AS': Error: 'status' does not point to a Class. at /var/www/html/oro-clean.loc/vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php:63, Doctrine\\ORM\\Query\\QueryException: SELECT o.id, o.name, o.createdAt, o.updatedAt, o.closeDate, o.probability, o.budgetAmount, o.closeRevenue, s.id as status, CONCAT(contactAlias.firstName, CONCAT(' ', contactAlias.lastName)) as contactName, contactAlias.id as contact, closeReason.label as closeReasonLabel, email.email as primaryEmail, channel.name as channelName, own.id as owner, CONCAT(own.firstName, CONCAT(' ', own.lastName)) as ownerName, customer.name as customerName, o.ac_contact_count as timesContacted, o.ac_contact_count_in as timesContactedIn, o.ac_contact_count_out as timesContactedOut, o.ac_last_contact_date as lastContactedDate, o.ac_last_contact_date_in as lastContactedDateIn, o.ac_last_contact_date_out as lastContactedDateOut, DATE_DIFF(CURRENT_DATE(), o.ac_last_contact_date) as daysSinceLastContact FROM OroCRM\\Bundle\\SalesBundle\\Entity\\Opportunity o LEFT JOIN o.contact contactAlias LEFT JOIN o.status s LEFT JOIN o.closeReason closeReason LEFT JOIN contactAlias.emails email WITH email.primary = true LEFT JOIN o.dataChannel channel LEFT JOIN o.owner own LEFT JOIN o.customer customer ORDER BY status.id ASC at /var/www/html/oro-clean.loc/vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php:41)"} []`

**Comment by glutaminefree** [comment]
Bump.

**Comment by artml** [comment]
@glutaminefree we are investigating the problem, sorry about the delay.

**Comment by mkudelya** [comment]
@glutaminefree We have already fixed this bug. It will be available in the next release. As the hot fix i suggest you replace original sales-opportunity-grid in file vendor/oro/crm/src/OroCRM/Bundle/SalesBundle/Resources/config/datagrid.yml and change

from
`status:
data_name: status.id`

to
`status:
data_name: status`

inside 'sorters' section

**Comment by glutaminefree** [comment]
@mkudelya and team, thanks for reaction!

**Comment by glutaminefree** [comment]
In section 'filters' on line 204 also need change from 'status.id' to 'status'.

```
status:
    type:      enum
    data_name: status
    enum_code: opportunity_status
```

**Comment by mkudelya** [comment]
@glutaminefree, yes, of course, thanks!
