### ISSUE TITLE
Installer exception...

### ISSUE THREAD

**Issue by corradomatt** [orocrm/crm#185]
`[RuntimeException]
  Failed migrations: Oro\Bundle\EmailBundle\Migrations\Schema\OroEmailBundleInstaller.`

Installing on...
- CentOS 7
- PHP 5.6
- MariaDB 5.5.47
- nginx

I've cloned to the server, created a DB and run the installer from a browser and command line. I've also cleared the app cache and tried to reinstall from command line. All permissions are set to the same owner and group that nginx and php-fpm share. Any ideas or tips?

**Comment by sergeyz** [comment]
Hi, @corradomatt! Please provide log file (`app/logs/{prod or dev}.log`)

**Comment by corradomatt** [comment]
Ok. One thing is that I tried running `php app/console oro:install --env prod -vvv --timeout 3600` and no log file was generated. However, when I ran the browser installer I got a `oro_install.log` and a `prod.log`. Here's the output from prod.log...
```
[2016-06-28 07:20:59] request.CRITICAL: Uncaught PHP Exception RuntimeException: "The command terminated with an exit code: 1." at /var/www/html/vendor/oro/platform/src/Oro/Bundle/InstallerBundle/CommandExecutor.php line 200 {"exception":"[object] (RuntimeException: The command terminated with an exit code: 1. at /var/www/html/vendor/oro/platform/src/Oro/Bundle/InstallerBundle/CommandExecutor.php:200)"} []
```

**Comment by sergeyz** [comment]
Any stacktrace few lines below?

**Comment by sergeyz** [comment]
Not sure it will help.

Before `[RuntimeException] Failed migrations: ` you have some skipped migrations, like

```
 > OroCRM\Bundle\ActivityContactBundle\Migration\ActivityContactMigration - skipped
```

and actual error right after failed migration executed
```
Oro\Bundle\EmailBundle\Migrations\Schema\OroEmailBundleInstaller
```

That message will help to understand whats is going on

See https://github.com/orocrm/crm/issues/143#issuecomment-164752970 for more details how to find that message

**Comment by artml** [comment]
no response from the reporter so I'm closing it for now. @corradomatt feel free to reopen anytime
