### ISSUE TITLE
Unable to add a channel with a new entity ?

### ISSUE THREAD

**Issue by mikeSimonson** [orocrm/crm#186]
Hi,

For some reason I can't add any new channel in the Account or Contact view.

I created a new entity. It's linked to the Account entity and the Contact entity.

```
@ORM\ManyToOne(targetEntity="OroCRM\Bundle\AccountBundle\Entity\Account")
```

I added the datagrid configuration and the navigation configuration.

The menu show up and the datagrid works perfectly.

I added a custom channel to try and link that new entity to the customer, but it never show up in the channels of the Account view.

What needs to be changed so that it show up there ?

Thanks

**Comment by artml** [comment]
@mikeSimonson by custom channel you mean the Custom option in the channel creation dialog, or a completely custom channel you've developed?

**Comment by mikeSimonson** [comment]
@artml The Custom option in the channel creation.
It has the customer identity by default and I added my Entity to it.

**Comment by artml** [comment]
@mikeSimonson oh, I see. Unfortunately, this option is not really usable :-( that customer identity entity has no view and doesn't appear on the account view either.

This is a known issue and we should've fixed it long ago, but it is as it is now. Sorry about that.

The only viable option for custom channels now is to actually develop a new channel type, define your customer type along with it, and change the Account view accordingly. No UI options are available.

**Comment by mikeSimonson** [comment]
@artml Can you point to any documentation on how to build a new channel type ?
When you say define your cutomer type, I guess you mean custom entity ?
And by changing the Account view you mean overriding it and adding a block into it ?

**Comment by artml** [comment]
@mikeSimonson our [Channel bundle doc](https://github.com/orocrm/crm/tree/master/src/OroCRM/Bundle/ChannelBundle) should be a good start.

New customer type should be a custom entity, yes.

**Comment by wimg** [comment]
To clarify : we're not talking about a new customer type. We'd like to add an entity to the standard account view, so that we can show related items to that account in a grid.

I looked at the channel bundle documentation, but it's rather limited. Do you know of any open source projects that we could use as a reference ?

**Comment by 24198** [comment]
@wimg,

This doesn't sound like something you want to solve through a channel. If you want to show related items for an Account you could create an additional relation, which from what I've read so far has been done, and add the grid of that new entity to the Account view.

If I'm missing something in the process here, as in missing the point what you're trying to accomplish, please let me know.

Hope this helps.

Kind Regards,

Jaimy

**Comment by mikeSimonson** [comment]
@24198 What is the proper way to add the grid in the Account view ?

**Comment by 24198** [comment]
@mikeSimonson Theoretically you could extend the `OroCRM/AccountBundle/Resources/views/Account/view.html.twig` and add your own datagrid by importing `{% import 'OroDataGridBundle::macros.html.twig' as dataGrid %}` and rendering it like `{{ dataGrid.renderGrid(gridName) }}`

I was trying to create a quick example, but my dev environment decided that I've done enough damage to it, so I'm sorry. I'm still going to try and see if I can get an example up though, I'll keep you posted.


Kind Regards,

Jaimy

**Comment by 24198** [comment]
@mikeSimonson 

I've created a small demo bundle [AccountViewDemoBundle](https://github.com/24198/AccountViewDemoBundle/blob/master/AccountViewDemoBundle/composer.json). Hope it helps.

Kind Regards,


Jaimy

**Comment by artml** [comment]
A quick update here: while developing 2.0 version we have decided we are going to phase channels out before the next LTS release, therefore we won't add or expand any functionality related to them. So I am closing this issue.
