### ISSUE TITLE
Alignement of contacts in account page

### ISSUE THREAD

**Issue by sadortun** [orocrm/crm#188]
One last UI issue !! 

When a single contact have a Email and phone, the contacts are incorectly alligned. This is due to the each `<a>` tags that add 2px in the height of the dif, for a total of 4px

![image](https://cloud.githubusercontent.com/assets/794449/16475101/d8114e76-3e49-11e6-963f-d1a8ad3da518.png)

**Comment by artml** [comment]
@sadortun thanks for the report! Would like to see it fixed before the release, but it's not a major issue, so it might have to wait for the future minor bugfix release.

**Comment by sadortun** [comment]
If I submit a PR with the CSS tweaks, would it help, or it more overhead to merge the PR that fixing it yourself ?

**Comment by artml** [comment]
@Grygir what would work better for you?

**Comment by Grygir** [comment]
@sadortun thanks for willingness to help. The contribution would help us.
