### ISSUE TITLE
Error while deleting a field entity through the ui

### ISSUE THREAD

**Issue by tigitz** [orocrm/crm#195]
Hello,

Using master version of crm-application I have an error while trying to delete a field of an entity.

**Oro version**

> oro/crm                                  dev-master c2375b0 OroCRM
> oro/platform                             dev-master e32eeb8 Business Application Platform (BAP)

**The ajax request:**

> http://localhost:8872/app_dev.php/actionajax/operation/execute/DELETE?datagrid=entityfields-grid&entityClass=Oro%5CBundle%5CEntityConfigBundle%5CEntity%5CFieldConfigModel&entityId=679

**The error message:**

> "The class 'Oro\Bundle\EntityConfigBundle\Entity\FieldConfigModel' was not found in the chain configured namespaces Oro\Bundle\OrganizationBundle\Entity, Oro\Bundle\SecurityBundle\Entity, Oro\Bundle\AttachmentBundle\Entity, Oro\Bundle\EmailBundle\Entity, Oro\Bundle\CronBundle\Entity, Oro\Bundle\UserBundle\Entity, Oro\Bundle\EntityBundle\Entity, Oro\Bundle\EntityExtendBundle\Entity, Oro\Bundle\IntegrationBundle\Entity, Akeneo\Bundle\BatchBundle\Entity, Oro\Bundle\ActivityBundle\Entity, Oro\Bundle\ActivityListBundle\Entity, Oro\Bundle\AddressBundle\Entity, Oro\Bundle\BusinessEntitiesBundle\Entity, Oro\Bundle\CalendarBundle\Entity, Oro\Bundle\DataAuditBundle\Entity, Oro\Bundle\DataGridBundle\Entity, Oro\Bundle\EmbeddedFormBundle\Entity, Oro\Bundle\FormBundle\Entity, Oro\Bundle\ImapBundle\Entity, Oro\Bundle\MigrationBundle\Entity, Oro\Bundle\NoteBundle\Entity, Oro\Bundle\NotificationBundle\Entity, Oro\Bundle\ReportBundle\Entity, Oro\Bundle\SegmentBundle\Entity, Oro\Bundle\SidebarBundle\Entity, Oro\Bundle\SoapBundle\Entity, Oro\Bundle\TagBundle\Entity, Oro\Bundle\TranslationBundle\Entity, Oro\Bundle\WindowsBundle\Entity, Oro\Bundle\WorkflowBundle\Entity, Oro\Bundle\CommentBundle\Entity, Oro\Bundle\DashboardBundle\Entity, Oro\Bundle\NavigationBundle\Entity, OroCRM\Bundle\ContactBundle\Entity, OroCRM\Bundle\AccountBundle\Entity, OroCRM\Bundle\MarketingListBundle\Entity, Oro\Bundle\TrackingBundle\Entity, Oro\Bundle\ReminderBundle\Entity, OroCRM\Bundle\CallBundle\Entity, OroCRM\Bundle\CampaignBundle\Entity, OroCRM\Bundle\ChannelBundle\Entity, OroCRM\Bundle\TaskBundle\Entity, OroCRM\Bundle\AnalyticsBundle\Entity, OroCRM\Bundle\SalesBundle\Entity, OroCRM\Bundle\ContactUsBundle\Entity, OroCRM\Bundle\MagentoBundle\Entity, OroCRM\Bundle\CaseBundle\Entity, OroEntityProxy\OroEmailBundle, Oro\Bundle\EntityConfigBundle\Audit\Entity, Extend\Entity, JMS\JobQueueBundle\Entity"

**Comment by mkudelya** [comment]
@tigitz 
Hi,
Do you click at Delete icon on System -> Entities -> Entity Management -> [Some Entity] -> Entity field ? If yes, it is strange, because my ajax call for User -> Title field is http://orocrm-application.local/app_dev.php/entity/extend/field/remove/1048

**Comment by artml** [comment]
Closed due to no feedback
