### ISSUE TITLE
Loading... After login application is struck onloading

### ISSUE THREAD

**Issue by achyuth** [orocrm/crm#196]
Hi All, 

Any one has an-idea about this 

![crm_loading_issue](https://cloud.githubusercontent.com/assets/1415238/16906379/58bd6012-4cd4-11e6-86c6-efffcec6a17c.jpg)

**Comment by sadortun** [comment]
You can try the following :
```
php app/console cache:clear --env=dev --no-debug
php app/console cache:clear --env=prod --no-debug

php app/console --env=prod oro:platform:update  --force
```

**Comment by achyuth** [comment]
Thanks a lot , Its work.

**Comment by achyuth** [comment]
@sadortun is there any better way to learn about OROCRM as developer, I am very new to this framework.

**Comment by sadortun** [comment]
Hi @achyuth  

There is a couple of ressources :
[https://www.orocrm.com/documentation/developers](https://www.orocrm.com/documentation/developers)

- The Oro Book
- The Oro Cookbook
- The Oro Bundles
- User Guide
- Community Guide

And the forum : [https://www.orocrm.com/forums](https://www.orocrm.com/forums)

You can also lean a lot by going throuh  the list of issues and PR on both orocrm and platform repositories.

**Comment by achyuth** [comment]
Hi @sadortun 

It seems first we need to understand Symfony.

**Comment by sadortun** [comment]
Indeed...

[http://symfony.com/doc/2.8/book/index.html](http://symfony.com/doc/2.8/book/index.html)

**Comment by achyuth** [comment]
one last question What is basic deference between OROCRM and OroPlatform?

**Comment by sadortun** [comment]
OroCRM is built on top of OroPlatform.
You can have a look  [https://github.com/orocrm/crm/tree/master/src/OroCRM/Bundle](https://github.com/orocrm/crm/tree/master/src/OroCRM/Bundle)  and [https://github.com/orocrm/platform/tree/master/src/Oro/Bundle](https://github.com/orocrm/platform/tree/master/src/Oro/Bundle) for the list of components in each projects
