### ISSUE TITLE
Composer version issues

### ISSUE THREAD

**Issue by rolandoanton** [orocrm/crm#199]
The last version 1.2.0 (2016-07-18) is not working for deploy the oro/crm package, after serveral tests I found that the 1.0.0 version of composer works.

**Comment by alex-n-2k7** [comment]
Hi @rolandoanton 
We are working on this issue now and the fix will be available soon .
The v1.2.0 works fine, but the solution requires some minor changes (related to changes in Composer itself) in Oro\Bundle\DistributionBundle\Manager\PackageManager.

Actually, I do not know the yours exactly case, so please provide Steps To Reproduce.
I've been testing deploying oro/crm package from installed oro/platform - it works.
So if this is the same case and you need the solution asap I can share the changes in PackageManager here.
