### ISSUE TITLE
Not able to install crm on ubuntu

### ISSUE THREAD

**Issue by alivemindev** [orocrm/crm#200]
...
Load "Title Templates" from annotations and config files to db
Completed
Dumping exposed routes.

[file+] web/js/routes.js
18:05:57 [file+] oro.locale_data.js
Installing assets as hard copies.
...[skipped]...
Installing assets for Oro\Bundle\FormBundle into web/bundles/oroform
...[skipped]...
Dumping all prod assets.
Debug mode is off.

18:05:59 [file+] /var/www/html/crm/crm-application/app/../web/bundles/tinymce/tinymce.min.js
18:05:59 [file+] /var/www/html/crm/crm-application/app/../web/bundles/tinymce/jquery.tinymce.min.js
18:05:59 [file+] /var/www/html/crm/crm-application/app/../web/bundles/tinymce/plugins/bdesk_photo/plugin.min.js

  [RuntimeException]
  The source file "/var/www/html/crm/crm-application/app/../web/bundles/oroform/lib/bdeskphoto/plugin.min.js" does not exist.

assetic:dump [--watch] [--force] [--period PERIOD] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-s|--shell] [--process-isolation] [-e|--env ENV] [--no-debug] [--jms-job-id JMS-JOB-ID] [--current-user CURRENT-USER] [--current-organization CURRENT-ORGANIZATION] [--disabled-listeners DISABLED-LISTENERS] [--] <command> [<write_to>]

  [RuntimeException]
  The command terminated with an exit code: 1.

Exception trace:
 () at /var/www/html/crm/crm-application/vendor/oro/platform/src/Oro/Bundle/InstallerBundle/CommandExecutor.php:200
 Oro\Bundle\InstallerBundle\CommandExecutor->processResult() at /var/www/html/crm/crm-application/vendor/oro/platform/src/Oro/Bundle/InstallerBundle/CommandExecutor.php:143
 Oro\Bundle\InstallerBundle\CommandExecutor->runCommand() at /var/www/html/crm/crm-application/vendor/oro/platform/src/Oro/Bundle/InstallerBundle/Command/InstallCommand.php:507
 Oro\Bundle\InstallerBundle\Command\InstallCommand->finalStep() at /var/www/html/crm/crm-application/vendor/oro/platform/src/Oro/Bundle/InstallerBundle/Command/InstallCommand.php:111
 Oro\Bundle\InstallerBundle\Command\InstallCommand->execute() at /var/www/html/crm/crm-application/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:259
 Symfony\Component\Console\Command\Command->run() at /var/www/html/crm/crm-application/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:886
 Symfony\Component\Console\Application->doRunCommand() at /var/www/html/crm/crm-application/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:195
 Symfony\Component\Console\Application->doRun() at /var/www/html/crm/crm-application/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:96
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /var/www/html/crm/crm-application/vendor/jms/job-queue-bundle/JMS/JobQueueBundle/Console/Application.php:45
 JMS\JobQueueBundle\Console\Application->doRun() at /var/www/html/crm/crm-application/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:126
 Symfony\Component\Console\Application->run() at /var/www/html/crm/crm-application/app/console:23

**Comment by mbessolov** [comment]
@alivemindev  what version are you trying to install? The installation completes successfully on master as well as on the release versions.

**Comment by alivemindev** [comment]
I am using latest version 1.9.6

**Comment by mkudelya** [comment]
@alivemindev Which command (-s) are you using to install your orocrm ? For example my command:

app/console oro:install --env=prod --force --user-name=admin --timeout=3000 --user-email=admin@example.com --user-firstname=John --user-lastname=Doe --user-password=admin --sample-data=y --organization-name=OroCRM --application-url=http://orocrm.local

Before installation does /web/bundles folder contain bundles folders with js/css data ?

**Comment by alivemindev** [comment]
"php /var/www/html/crm/crm-application-old/app/console oro:install --env prod -vvv"
this command i am using for installation.

**Comment by mkudelya** [comment]
Try to go to your project root directory, in your case it is 'var/www/html/crm/crm-application-old'
and run 'app/console oro:install --force --drop-database --env prod -vvv'
