### ISSUE TITLE
Access restrictions on field level ?

### ISSUE THREAD

**Issue by wimg** [orocrm/crm#201]
Is there a way to restrict who can see and/or edit which fields of an entity ?

**Comment by artml** [comment]
@wimg not yet, but it will be released on Monday as part of 1.10 :)

**Comment by mikeSimonson** [comment]
Where is that feature in the UI or the doc on how to use it ?

**Comment by yurio** [comment]
@mikeSimonson, some info about Field ACL you can find here https://github.com/orocrm/platform/blob/master/src/Oro/Bundle/SecurityBundle/Resources/doc/field-acl.md
and here https://github.com/orocrm/platform/blob/master/src/Oro/Bundle/DataGridBundle/Resources/doc/backend/extensions/field_acl.md

By default, Field ACL is turned off. 
But you can turn it for Opportunity and Lead entities from the CRM.

For other entities, you should enable it as was described at the documentation.
