### ISSUE TITLE
Access restrictions on field level ? (reopened)

### ISSUE THREAD

**Issue by wimg** [orocrm/crm#206]
The previous issue was closed, so coming back to this one.
I understand this is available in 1.10, but where exactly does it show up in the UI ? I looked under roles, entities and directly under user, but can only find restrictions on entity level, not field level.

**Comment by DimaSoroka** [comment]
Field level ACL should be enabled on the entity level first. Currently we implemented it for account and Opportunity entity so once you enable it via entity manager role management UI will provide access to entity fields management.

1. Go to System > Entity > Entity Management
2. Find Account entity and edit it
3. Set checkbox for "Field Level ACL" in "Other" section
4. Go to System > User Management > Roles
5. Edit any role and you will see "+" icon on the account entity
6. Change field access permissions

**Comment by wimg** [comment]
I'll give it a try, as soon as I get it working (see #207 )

**Comment by mikeSimonson** [comment]
@DimaSoroka How much work would it be to add it to other entities like contact ?

**Comment by DimaSoroka** [comment]
Not much, it mostly will require refactor of contact view template.

**Comment by mkudelya** [comment]
I am now closing this issue as it has been inactive for a while. Please, feel free to reopen it if you have any questions.
