### ISSUE TITLE
Unrecognized option "entity_aliases" under "oro_api"

### ISSUE THREAD

**Issue by wimg** [orocrm/crm#207]
After doing a clean install of 1.10, when running app/console I get :

PHP Fatal error:  Uncaught exception 'Symfony\Component\Config\Definition\Exception\InvalidConfigurationException' with message 'Unrecognized option "entity_aliases" under "oro_api"' in /web/content/somewhere/vendor/symfony/symfony/src/Symfony/Component/Config/Definition/ArrayNode.php:309
Stack trace:
#0 /web/content/somewhere/vendor/symfony/symfony/src/Symfony/Component/Config/Definition/BaseNode.php(264): Symfony\Component\Config\Definition\ArrayNode->normalizeValue(Array)
#1 /web/content/somewhere/vendor/symfony/symfony/src/Symfony/Component/Config/Definition/Processor.php(33): Symfony\Component\Config\Definition\BaseNode->normalize(Array)
#2 /web/content/somewhere/vendor/symfony/symfony/src/Symfony/Component/Config/Definition/Processor.php(50): Symfony\Component\Config\Definition\Processor->process(Object(Symfony\Component\Config\Definition\ArrayNode), Array)
#3 /web/content/somewhere/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Extension/Extension.php(105): Symfony\Compone in /web/content/somewhere/vendor/symfony/symfony/src/Symfony/Component/Config/Definition/ArrayNode.php on line 309

Same thing happens when trying to browse to it.

**Comment by vsoroka** [comment]
May be you forgot to remove the cache before run "oro:install" command? Actually "entity_aliases" is allowed option in "api.yml" config. See https://github.com/orocrm/platform/blob/1.10/src/Oro/Bundle/ApiBundle/Config/Definition/ApiConfiguration.php#L96-L107.

**Comment by wimg** [comment]
This was a brand new install. New directory, new database, etc.

**Comment by vsoroka** [comment]
It is very strange, I've just installed crm 1.10 and it works fine. I've did the following steps:
- git clone -b 1.10 git@github.com:orocrm/crm-application.git
- composer install
- create database
- php app/console oro:install --env=prod

Next, to check that all is ok, I've run the following commands:
php app/console --env=prod - this command is executed without any problems
php app/console oro:api:dump --env=prod - this command is executed without any problems as well

**Comment by artml** [comment]
No response from @wimg so I assume this has been sorted out. Wim, feel free to reopen the issue if it's not.
