### ISSUE TITLE
Upgrade to  Version 1.10

### ISSUE THREAD

**Issue by golrizSayeh** [orocrm/crm#208]
I try to change my orocrm version from 8.2 to 10 so follow this link
https://www.orocrm.com/documentation/index/current/cookbook/how-to-upgrade-to-new-version
All thing was OK until I run : 
$ sudo -u www-data php app/console oro:platform:update --env prod --force
 in middle of migration I get below error:
.
.
.
.

> OroCRM\Bundle\CaseBundle\Migrations\Schema\v1_8\CreateActivityAssociation
> Oro\CRMCallBridgeBundle\Migrations\Schema\OroCRMCallBridgeBundleInstaller
> Oro\CRMTaskBundle\Migrations\Schema\OroCRMTaskBundleInstaller
> Oro\Bundle\MigrationBundle\Migration\UpdateBundleVersionMigration
> Oro\Bundle\EntityExtendBundle\Migration\RefreshExtendCacheMigration

  [ErrorException]  
  Catchable Fatal Error: Argument 1 passed to Oro\Bundle\ConfigBundle\Config\AbstractScopeManager::__construct() must implement interface Doctrine\Common\Persistence\ManagerRegistry, instance of Oro\Bundle\EntityBundle\ORM\OroEntityManager given, called in /home/golriz/public_html/app/cache/prod/appProdProjectContainer.php on line 140 and defined in /home/golriz/public_html/vendor/oro/platform/src/Oro/Bundle/ConfigBundle/Config/AbstractScopeManager.php on line 31  

---

could you help ?

**Comment by mkudelya** [comment]
Hi @golrizSayeh,

Your cache contains old constructor function, please delete /app/cache/prod directory and try again.

**Comment by golrizSayeh** [comment]
Hi @mkudelya 
I was deleted cache before update of platform by sudo rm -rf app/cache/*
but again I have this problem !!

**Comment by mkudelya** [comment]
Hi,

Try to again clear all caches and run 'php app/console oro:platform:update --env dev --force' command, after that run 'php app/console cache:clear --env prod'

**Comment by golrizSayeh** [comment]
Dear @mkudelya 
thanks for you answer. I see that I had used AbstractScopeManager in my src , I change my services according to new version of AbstractScopeManager , and it solved
So I pass that step but I see another problem 
..
.
.
.
  > loading Oro\Bundle\ImapBundle\Migrations\Data\ORM\ClearInactiveMailboxes
  > loading Oro\Bundle\CalendarBundle\Migrations\Data\ORM\LoadAttendeeData

                                                              
  [Doctrine\Common\Persistence\Mapping\MappingException]      
  Class 'Extend\Entity\EV_Ce_Attendee_Status' does not exist  

.
I run php app/console cache:clear --env prod and  sudo rm -rf app/cache/*  before run platform:update

**Comment by mkudelya** [comment]
Hi,

Did you run 'php app/console oro:platform:update --env dev --force' or 'php app/console oro:platform:update --env prod --force' ? Try to in dev mode, after that run 'php app/console cache:clear --env prod'

**Comment by golrizSayeh** [comment]
Yes I run prod mode
if I run dev mode it show me below error

PHP Fatal error:  Uncaught exception 'Oro\Bundle\EntityBundle\Exception\EntityAliasNotFoundException' with message 'A plural alias for "Extend\Entity\EV_Lead_Source" entity not found.' in /home/public_html/vendor/oro/platform/src/Oro/Bundle/EntityBundle/ORM/EntityAliasResolver.php:92
:(

**Comment by mkudelya** [comment]
@golrizSayeh 
This is known issue we are working on it. I suggest you run update again after error without cache clearing. Thank you for your patience.

**Comment by golrizSayeh** [comment]
Dears
I Update platform to 1.10.2 but again I see error.
I see that below code in entity.yml of salesBundle 
        Extend\Entity\EV_Lead_Status:
            alias:        salesleadstatus
            plural_alias: salesleadstatuses 
so I add a plural_alias for EV_Lead_Source
        Extend\Entity\EV_Lead_Source:
            alias:        salesleadsource
            plural_alias: salesleadsources
after that I have same problem for : 
- Extend\Entity\EV_Lead_Ea129965
- Extend\Entity\EV_Vendor_B4a14066
- Extend\Entity\EV_Task_Status
...

**Comment by sergeyz** [comment]
Hi, @golrizSayeh, please check this issue on https://github.com/orocrm/platform/releases/tag/1.10.3 version

**Comment by mkudelya** [comment]
Hi @golrizSayeh 

Do you have any issues on newest 1.10.* version ?

**Comment by JacerOmri** [comment]
maybe this is related;

I'm using oro:install to make a fresh install for a project i just upgraded to 1.10.15, i have this issue:

```
  > loading Oro\Bundle\CalendarBundle\Migrations\Data\ORM\LoadAttendeeData

                                                              
  [Doctrine\Common\Persistence\Mapping\MappingException]      
  Class 'Extend\Entity\EV_Ce_Attendee_Status' does not exist  
```

Tried clearing cache, EntityConfig... couldn't get it to work.

**Comment by mkudelya** [comment]
Hi @JacerOmri 

Could you please tell me which version of OroCRM you had before the upgrade to 1.10.15? I would like to try and emulate your upgrade flow. We have a [document](https://www.orocrm.com/documentation/1.10/cookbook/how-to-upgrade-to-new-version) which explains how to upgrade to a new version. Did you follow the instructions outlined there by any chance?

**Comment by mkudelya** [comment]
I am now closing this issue as it has been inactive for a while. Please, feel free to reopen it if you have any questions.
