### ISSUE TITLE
Require fixed platform version

### ISSUE THREAD

**Issue by sbani** [orocrm/crm#210]
Hi,

as I see you forgot the slack channel conversation we had:
Please use a fixed version for `oro/platform` in composer json because there will be problems in `oro/platform-application` if you want an older version of `oro/crm`.

As long as the platform is not developed standalone and you don't use semantic versioning, the application will be broken.

Example:
```json
    "require": {
        "oro/crm": "1.10.1",
    },
```
If you use `composer update` you install `oro/crm@1.10.1` but `oro/platform@1.10.2`.

Thanks

**Comment by sbani** [comment]
Let me ask one question:
Why is this scheduled for 2.0? Is this not important for each version?

PS: This is a one file one line change! This is not something which needs to be tested, discussed or prepared.

**Comment by DimaSoroka** [comment]
I'm not sure i'm clear on the issue itself, could you please explain why patch version of `oro/platfrom` should be changed from "1.10.*" to "1.10.x"?

**Comment by sbani** [comment]
Sure @DimaSoroka:

I informed the oro team in the slack channel and here at Github in June (https://github.com/orocrm/platform/issues/472#issuecomment-226692054) about your **returning problems with semantic versioning**. Your team seem to miss basic knowledge in this topic.

In theory you are completely correct that `oro/crm@1.10.0` *should* be able to use `oro/platform@1.10.5`, but I'm very sure that this is not the case. It starts with the fact that there are still UPGRADE.md files for patch versions (UPGRADE-1.10.1.md). This is per definition wrong! If I need to "upgrade" my own app for that version, it's not a patch version - because there is an "public api" change.

Again the side note:
As you can see in the platform [composer.json](https://github.com/orocrm/platform/blob/master/composer.json#L76), you require for example `"oro/jsplumb": "~1.7"` which can lead to any version below 2.0.0 (e.g. `1.9.3`). An update from 1.7 to 1.9 is likely to fail which is totally okay from the vendor's view, but not for you!

I think @DimaSoroka, that you should talk with your team and introduce semver officially with a small training and when you do that you should give a git introduction too.

**Git and semver are two things that cost you a little training, but will lead to a significant improvement with code and design quality.**

**Comment by DimaSoroka** [comment]
Got you, thanks for detail info!
We are committing to support backward compatibility withing PATCH version number so if you see any issues with any upcoming patch version number please let us know (no more UPGRADE-1.10.1.md).

We can't commit to semver in scope of MINOR version release yet, but this is our next target.

I'm closing this issue as with our backward compatibility promise on PATCH version release there are no need to lock PATCH version number. If you have any issues with any previous releases and would like lock version there we will be happy to process PR.

**Comment by sbani** [comment]
Hope you can keep your promise and I'm really looking forward to use a semver compatible or with clean git logs.

Thank you very much @DimaSoroka.
