### ISSUE TITLE
extend the dropdown button in contact view

### ISSUE THREAD

**Issue by mikeSimonson** [orocrm/crm#217]
In the contact view template there is code for the delete and the edit button but I can't find a way to add a link in the dropdown button that is just on the right of those 2.

How is it possible to add a link in that dropdown ?

Thanks

**Comment by mkudelya** [comment]
Hi,

You should create two [placeholders](https://github.com/orocrm/platform/blob/1.10/src/Oro/Bundle/NoteBundle/Resources/config/placeholders.yml#L4-L12) with templates and [register it](https://github.com/orocrm/platform/blob/1.10/src/Oro/Bundle/NoteBundle/Resources/config/services.yml#L61-L68).

**Comment by mkudelya** [comment]
I am now closing this issue as it has been inactive for a while. Please, feel free to reopen it if you have any questions.
