### ISSUE TITLE
Manage segments is broken in Spanish Language 

### ISSUE THREAD

**Issue by zoniko** [orocrm/crm#224]
app.php/segments frezees and keeps showing the 'loader-mask' forever. This happens when the application is set to spanish, if I change the locale to English the view works fine.

Any clue on this?

Thanks

**Comment by mkudelya** [comment]
Hi @zoniko 
Which version are you using ? Can you show me javascript or log error (app/logs), please?

**Comment by sbani** [comment]
@zoniko: you can check if this helps you: orocrm/platform#321

**Comment by mkudelya** [comment]
I am now closing this issue as it has been inactive for a while. Please, feel free to reopen it if you have any questions.
