### ISSUE TITLE
bug on Account panel using another user

### ISSUE THREAD

**Issue by AdriwanKenoby** [orocrm/crm#229]
I have this error when i am connect with another user than admin and i try to access to account panel, the user come from another businessUnits

> Variable "isExportPopupRequired" does not exist in vendor/oro/platform/src/Oro/Bundle/ImportExportBundle/Resources/views/ImportExport/buttons.html.twig at line 146

**Comment by mkudelya** [comment]
Hi @AdriwanKenoby 

Thanks you for your report. Fix will available in the next release of 1.10 version. As workaround i suggest you replace [this](https://github.com/orocrm/platform/blob/1.10/src/Oro/Bundle/ImportExportBundle/Resources/views/ImportExport/buttons.html.twig#L142) following code:

`{% if exportAllowed and hasExportProcessor %}`

**Comment by mkudelya** [comment]
I am now closing this issue as it has been fixed. Please, feel free to reopen it if you have any questions.
