### ISSUE TITLE
Call info dialog widget broken in dev mode

### ISSUE THREAD

**Issue by alsma** [orocrm/crm#232]
Hi.

"Call info" widget throws 500th in DEV mode if open it by clicking on subject from "recent calls" (see screenshot)
I've found out why this happens, so the reason is missing check [here](https://github.com/orocrm/OroCRMCallBundle/blob/master/Resources/views/Call/widget/info.html.twig#L10) as `target` argument is required by macros, but controller may produce null [there](https://github.com/orocrm/OroCRMCallBundle/blob/master/Controller/CallController.php#L194)

<img width="1035" alt="screen shot 2016-12-23 at 02 08 31" src="https://cloud.githubusercontent.com/assets/3245855/21444305/ddf3b8b0-c8b4-11e6-825e-cfe084951338.png">

**Comment by mkudelya** [comment]
Hi @alsma 

Thank you for your report!

**Comment by mkudelya** [comment]
I have just tested your use case but I found no issues with Recent Calls widget. Probably the issue has been fixed. I am now closing this issue. If you happen to have any questions, please feel free to reopen it.
Thank you!
