### ISSUE TITLE
Importing customer records from Magento setting incorrect Region

### ISSUE THREAD

**Issue by dajve** [orocrm/crm#233]
Seen on OroCRM EE editions 1.11.x and 1.12.x using MagentoBridge 1.2.5

To replicate:

- Configure integration with Magento site
- Create customer in Magento site with address with "State/Province" value `-`
- Sync customer data from Magento into Oro
- Customer has `OroCRMMagentoBundle:Address` association with Region set to "Alabama"

**Comment by mkudelya** [comment]
Hi @dajve 

'State/Province' is required select box field, how to set - (minus) value to it ? Did you add customer on via admin, account page or programmatically?

**Comment by dajve** [comment]
Hi @mkudelya 

State/Province is only a select box for certain countries - these are addresses from the UK, where the State/Province box is a simple text input.

I'm not sure if it was the client's decision to enter "-" or the customer themselves, however it is a valid value for addresses in the UK.

Kind regards,
Dajve

**Comment by mkudelya** [comment]
Hi

I have tried import customers on 1.12.12 EE and OroCRM Bridge 1.2.8. Here is screenshots:

Magento side:

![](http://image.prntscr.com/image/a993d25b66b1483c934841bbac2bdb72.png)

Oro side:

![](http://image.prntscr.com/image/f6d8cabb1691499a87511ac94cf99e4c.png)

For now available [1.2.10](https://www.magentocommerce.com/magento-connect/orocrm-bridge.html) version, try to upgrade.

**Comment by mkudelya** [comment]
Hi @dajve 

I am now closing this issue as, unfortunately, we have not received any feedback from you. Please, feel free to reopen it if you have any questions.

**Comment by dajve** [comment]
Hi @mkudelya 

Apologies - I completely missed this and have only just realised I didn't provide feedback on it! Sorry about that.

For posterity, we discovered the root cause of the issue, which was on the Magento side and not the Oro side. In the version of the checkout extension used by the client in question, there is the following code:

```
        if( $this->settings['exclude_region'] || (empty($data['region']) && empty($data['region_id'])))    {
            $data['region'] = '-';
            $data['region_id'] = '1';
        }
```

I'm not sure why it decided to default to region_id 1, rather than 0 (or empty), but this was the issue. As the addresses were in the UK, which didn't use an enum for its region, this wasn't output when viewing the record but was being sent across when an API call was made.

Kind regards,
Dajve
