### ISSUE TITLE
 Not required Russian language

### ISSUE THREAD

**Issue by Koevo** [orocrm/crm#239]
System/ Localization/ Languages
click on Install 

spinning load and nothing happens
[http://i91.fastpic.ru/big/2017/0129/e2/24bb794df4fc4fb95d659aaec4d8b4e2.jpg](url)

**Comment by mkudelya** [comment]
Hi @Koevo 

I will answer [here](https://www.orocrm.com/forums/topic/%D0%BF%D1%80%D0%BE%D0%B1%D0%BB%D0%B5%D0%BC%D0%B0-%D1%81-%D1%83%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%BE%D0%B9-%D1%80%D1%83%D1%81%D1%81%D0%BA%D0%BE%D0%B3%D0%BE-%D1%8F%D0%B7%D1%8B%D0%BA%D0%B0)

**Comment by Koevo** [comment]
Thank you. There, too, I))

**Comment by mkudelya** [comment]
I am now closing this issue. Please, feel free to reopen it if you have any questions.
