### ISSUE TITLE
Conversation threads in ActivityContactBundle?

### ISSUE THREAD

**Issue by VinnyVicious** [orocrm/crm#245]
I’m trying to create a small channel for customer-operator email-based conversations. I have an entity that i just created using your cookbook, called Ticket, and i’m trying to attach the ActivityContactBundle to it. However, i can’t seem to start a conversation thread on top of that. The only thing the operator is able to do is to send emails, and whenever the customer replies, the entity is not updated.

Does anyone have any idea of what might be going on here?

**Comment by mkudelya** [comment]
Hi @VinnyVicious 

If i right understood that you need go to System -> Entities -> Entity Management -> [Your Entity] -> edit entity and enable Emails and Calls activities, click Save and Update Schema buttons.

![](http://image.prntscr.com/image/d838dea6f05449e28595d693f83223b0.png)

**Comment by VinnyVicious** [comment]
Yes, that's what i did. However, once the operator sends an email to a customer regarding that entity, all answers from that customer are not added back to that same entity. There's no conversation thread or anything. I can only send an email from the entity, no one can answer it.

**Comment by VinnyVicious** [comment]
@mkudelya ?

**Comment by mkudelya** [comment]
Hi @VinnyVicious 

The following steps should be able to help you:

- Configure your IMAP settings.
![2a59a6a781694fe1800827310ad531fd](https://cloud.githubusercontent.com/assets/3332593/23220594/293a0eea-f92b-11e6-9d10-e41cd4ee34f9.png)
- The primary email of your currently logged in user should be the same as the email in IMAP settings.
- Try to send an email from your custom entity and reply to it.
- Run `app/console oro:cron:imap-sync -vvv` to synchronize emails.
- View entity page should contain an email thread.

**Comment by mkudelya** [comment]
I am now closing this issue as it has been inactive for a while. Please, feel free to reopen it if you have any questions.
