### ISSUE TITLE
Add activity associations from ActivityContactBundle to new entity

### ISSUE THREAD

**Issue by VinnyVicious** [orocrm/crm#246]
Are migrations the only way of adding activity associations from the ActivityContactBundle to my new entity? I’ve created a new class and i wanted to associate it with the following activities:

```
$this->activityExtension->addActivityAssociation($schema, ‘oro_note’, ‘orocrm_case’);
$this->activityExtension->addActivityAssociation($schema, ‘oro_email’, ‘orocrm_case’);
```

WITHOUT having to run a migration?

**Comment by mkudelya** [comment]
Hi

I have [answered](https://github.com/orocrm/crm/issues/245) on your question about ActivityContactBundle. Also set 'Enable Notes' to Yes, when you editing your entity.

**Comment by VinnyVicious** [comment]
Those were different questions. #245 is about the functionality, this question is about how to implement it. How can i add activity associations from my code, instead of from the interface?

**Comment by VinnyVicious** [comment]
@mkudelya ?

**Comment by mkudelya** [comment]
Hi @VinnyVicious 

Unfortunately, creating activity associations within code (without migrations) can be fairly difficult. However, you could try having a look at how it was [implemented](https://github.com/orocrm/platform/blob/1.10/src/Oro/Bundle/WorkflowBundle/Field/FieldGenerator.php#L54) with the 'workflow item' and the 'workflow step'.

**Comment by mkudelya** [comment]
I am now closing this issue as it has been inactive for a while. Please, feel free to reopen it if you have any questions.
