### ISSUE TITLE
Change ownership type of Case entity

### ISSUE THREAD

**Issue by VinnyVicious** [orocrm/crm#247]
Is it possible to change the ownership type of the Case entity? Today, all cases MUST have a User associated with it. We should be able to change this to Organization or BU, or just allow it to be null. This requirement makes no sense.

**Comment by sadortun** [comment]
Related to #184

**Comment by mkudelya** [comment]
@VinnyVicious @sadortun 

Please read [forum topic](https://www.orocrm.com/forums/topic/change-ownership-configuration-of-orobundlecasebundleentitycaseentity).

**Comment by VinnyVicious** [comment]
That suggestion does not work for the ownership field, it's ignored.

**Comment by VinnyVicious** [comment]
@mkudelya ?

**Comment by mkudelya** [comment]
Hi @VinnyVicious 

Сurrently, the platform doesn't support changing ownership type, however, this [acticle](https://www.atwix.com/oro/change-or-remove-ownership-scope-in-orocrm-entity-configuration) describes how to change owner in config. Here is an extract from my ownership section:

    "ownership"={
    "owner_type"="BUSINESS_UNIT",
    "owner_field_name"="owner",
    "owner_column_name"="business_unit_owner_id"
    },

Also, I added many-to-one (Case <=> Business Unit) relation (business_unit_owner_id field) and finally I changed $owner field annotation in CaseEntity:

    @ORM\ManyToOne(targetEntity="Oro\Bundle\OrganizationBundle\Entity\BusinessUnit")
    @ORM\JoinColumn(name="business_unit_owner_id", referencedColumnName="id", onDelete="SET NULL")

Some steps may not be necessary and I haven't fully tested my changes but i archived the following result:

![](http://image.prntscr.com/image/fccfe0ad229649f3b847f4213018cbb4.png)

**Comment by VinnyVicious** [comment]
I tried extending the `CaseEntity` from `OroCaseBundle` but it is still owned by a User, not a Business Unit. The article you mentioned is for custom entities, not for inherited entities.

**Comment by mkudelya** [comment]
Hi @VinnyVicious 

Yes, the article is not for inherited entities and perhaps annotation is not inheritable, but you can try replacing the `CaseEntity` completely. In my [post](https://www.orocrm.com/forums/topic/how-to-override-parts-of-oro#post-23067), I described the way to do it.

**Comment by mkudelya** [comment]
I am now closing this issue as it has been inactive for a while. Please, feel free to reopen it if you have any questions.
