### ISSUE TITLE
TwoWaySync required to edit Magento Customer?

### ISSUE THREAD

**Issue by MikeOtown** [orocrm/crm#250]
Why does \OroCRM\Bundle\MagentoBundle\Model\ChannelSettingsProvider::isChannelApplicable() require TwoWaySync to be enabled?  This is preventing me from editing a Magento Customer.

public function isChannelApplicable($channelId, $checkExtension = true)
    {
        $isChannelApplicable = $this->isEnabled($channelId) && $this->isTwoWaySyncEnable($channelId);
  if ($checkExtension) {
            $isChannelApplicable = $isChannelApplicable && $this->isSupportedExtensionVersion($channelId);
        }
        return $isChannelApplicable;
    }

![image](https://cloud.githubusercontent.com/assets/18534728/23142666/23c59e76-f78b-11e6-8721-4731cc500425.png)

**Comment by sergeyz** [comment]
Hi, @MikeOtown!

That means if a customer came from Magento (has channel_id assigned) we should send your changes back to Magento, but we are not able to send changes without two-way sync. But you should be able to edit regular customer created in CRM. What are your expectations here?

**Comment by MikeOtown** [comment]
I just spent a couple of hours of my time and Oro Support time trying to figure out why I was not getting an Edit button the Customer.  I think you should be able to edit a Magento Customer even if 2 way sync is disabled or at the very least display a message explaining why there is no Edit button.

**Comment by sergeyz** [comment]
@MikeOtown one more case not to edit customers from Magento without two-way sync: edit a customer in OroCRM without sync, edit a customer in Magento, do a sync and lose data changes from OroCRM side. Do you expect an edit button that will display a flash message? Or label somewhere else?

**Comment by MikeOtown** [comment]
Also I think isChannelApplicable() is a bad name for a method that requires TwoWaySync.  Applicable to what?  How about "isChannelTwoWaySync()" ?

**Comment by sergeyz** [comment]
Please step into function call. Its `$this->isEnabled($channelId) && $this->isTwoWaySyncEnable($channelId)` and `$this->isSupportedExtensionVersion($channelId)` [inside](https://github.com/orocrm/crm/blob/master/src/Oro/Bundle/MagentoBundle/Model/ChannelSettingsProvider.php#L81-L87)
