### ISSUE TITLE
Search tool returns no results

### ISSUE THREAD

**Issue by aligalipcamli** [orocrm/crm#252]
I have just installed OroCrm 2.0.2 with sample data in Ubuntu 16.04 box. When I search a phrase through search tool, it returns "No results were found to match your search." although there are records. I changed nothing in the configuration. It is a fresh install. Best regards...

**Comment by sadortun** [comment]
Do you have your message queue configured and your cron ? https://github.com/orocrm/crm-application#installation

**Comment by aligalipcamli** [comment]
Thank you. I have them configured and now search tool works as expected. That was my fault.

**Comment by sadortun** [comment]
@artml you might want to consider displaying a notice message mentioning that "Search have noting indexed yet" and refer to instalation instructions. Seems to be a recurring issue!

**Comment by artml** [comment]
@sadortun thank you for the tip, I have added the ticket to our stabilization backlog. Hopefully we'll fix it before the 2.1 release.
