### ISSUE TITLE
Search is not working in orocrm 2.0 

### ISSUE THREAD

**Issue by kusgpt26** [orocrm/crm#254]
I am using orocrm 2.0 and i created some contacts. But that contacts  are not showing in search process. Same problem with account also. All together the search process of orocrm 2.0 is not working.

**Comment by sadortun** [comment]
#252 ?

**Comment by kusgpt26** [comment]
@sadortun  Thank You. Now search works.

**Comment by mkudelya** [comment]
I am now closing this issue as it has been resolved.
