### ISSUE TITLE
Cannot update on 2.0.1 to 2.0.3

### ISSUE THREAD

**Issue by HirokazuNishi** [orocrm/crm#255]
## Environment:
PHP Version: 7.0.14
Composer Version: 1.3.2
OS: Ubuntu Linux 16.04LTS
OroCRM: 2.0.1

## How to reproduce
just execute below command on crm root directory.

`php -dmemory_limit=3072M /usr/bin/composer update -vvv --no-dev --prefer-dist`

## Result

> Adding VCS repository bower-asset/fullcalendar
> Downloading https://api.github.com/repos/fullcalendar/fullcalendar
> Downloading https://api.github.com/repos/fullcalendar/fullcalendar/contents/bower.json?ref=master
> Downloading https://api.github.com/repos/fullcalendar/fullcalendar/commits/master
> Downloading https://api.github.com/repos/fullcalendar/fullcalendar/tags?per_page=100
> Downloading https://api.github.com/repos/fullcalendar/fullcalendar/git/refs/heads?per_page=100
> 
>                                                                         
>   [UnexpectedValueException]                                            
>   Could not parse version constraint >=~2: Invalid version string "~2"  
>                                                                         
> 
> Exception trace:
>  () at phar:///usr/bin/composer/vendor/composer/semver/src/VersionParser.php:485
>  Composer\Semver\VersionParser->parseConstraint() at phar:///usr/bin/composer/vendor/composer/semver/src/VersionParser.php:244
>  Composer\Semver\VersionParser->parseConstraints() at phar:///usr/bin/composer/src/Composer/Package/Version/VersionParser.php:27
>  Composer\Package\Version\VersionParser->parseConstraints() at phar:///usr/bin/composer/src/Composer/Package/Loader/ArrayLoader.php:241
>  Composer\Package\Loader\ArrayLoader->parseLinks() at phar:///usr/bin/composer/src/Composer/Package/Loader/ArrayLoader.php:124
>  Composer\Package\Loader\ArrayLoader->load() at /home/verite/.composer/vendor/fxp/composer-asset-plugin/Repository/AssetVcsRepository.php:174
>  Fxp\Composer\AssetPlugin\Repository\AssetVcsRepository->preInitBranchPackage() at /home/verite/.composer/vendor/fxp/composer-asset-plugin/Repository/AssetVcsRepository.php:138
>  Fxp\Composer\AssetPlugin\Repository\AssetVcsRepository->initBranches() at /home/verite/.composer/vendor/fxp/composer-asset-plugin/Repository/AssetVcsRepository.php:45
>  Fxp\Composer\AssetPlugin\Repository\AssetVcsRepository->initialize() at phar:///usr/bin/composer/src/Composer/Repository/ArrayRepository.php:185
>  Composer\Repository\ArrayRepository->getPackages() at phar:///usr/bin/composer/src/Composer/DependencyResolver/Pool.php:104
>  Composer\DependencyResolver\Pool->addRepository() at /home/verite/.composer/vendor/fxp/composer-asset-plugin/Repository/Util.php:61
>  Fxp\Composer\AssetPlugin\Repository\Util::addRepositoryInstance() at /home/verite/.composer/vendor/fxp/composer-asset-plugin/Repository/Util.php:40
>  Fxp\Composer\AssetPlugin\Repository\Util::addRepository() at /home/verite/.composer/vendor/fxp/composer-asset-plugin/Repository/AbstractAssetsRepository.php:140
>  Fxp\Composer\AssetPlugin\Repository\AbstractAssetsRepository->whatProvides() at phar:///usr/bin/composer/src/Composer/DependencyResolver/Pool.php:204
>  Composer\DependencyResolver\Pool->computeWhatProvides() at phar:///usr/bin/composer/src/Composer/DependencyResolver/Pool.php:193
>  Composer\DependencyResolver\Pool->whatProvides() at phar:///usr/bin/composer/src/Composer/DependencyResolver/RuleSetGenerator.php:161
>  Composer\DependencyResolver\RuleSetGenerator->whitelistFromPackage() at phar:///usr/bin/composer/src/Composer/DependencyResolver/RuleSetGenerator.php:322
>  Composer\DependencyResolver\RuleSetGenerator->getRulesFor() at phar:///usr/bin/composer/src/Composer/DependencyResolver/Solver.php:214
>  Composer\DependencyResolver\Solver->solve() at phar:///usr/bin/composer/src/Composer/Installer.php:472
>  Composer\Installer->doInstall() at phar:///usr/bin/composer/src/Composer/Installer.php:223
>  Composer\Installer->run() at phar:///usr/bin/composer/src/Composer/Command/UpdateCommand.php:158
>  Composer\Command\UpdateCommand->execute() at phar:///usr/bin/composer/vendor/symfony/console/Command/Command.php:257
>  Symfony\Component\Console\Command\Command->run() at phar:///usr/bin/composer/vendor/symfony/console/Application.php:850
>  Symfony\Component\Console\Application->doRunCommand() at phar:///usr/bin/composer/vendor/symfony/console/Application.php:193
>  Symfony\Component\Console\Application->doRun() at phar:///usr/bin/composer/src/Composer/Console/Application.php:227
>  Composer\Console\Application->doRun() at phar:///usr/bin/composer/vendor/symfony/console/Application.php:124
>  Symfony\Component\Console\Application->run() at phar:///usr/bin/composer/src/Composer/Console/Application.php:100
>  Composer\Console\Application->run() at phar:///usr/bin/composer/bin/composer:54
>  require() at /usr/bin/composer:24

## Expected result:
Update from OroCRM 2.0.1 to 2.0.3 via composer

**Comment by mkudelya** [comment]
Hi @HirokazuNishi 

Thanks for the post! It is a known issue which I [wrote](https://github.com/orocrm/platform/pull/649#issuecomment-284359897) about yesterday. Sorry for the inconvenience!

**Comment by HirokazuNishi** [comment]
Ohhh, sounds good. Thanks!
