### ISSUE TITLE
Problem after installation orocrm 2.0

### ISSUE THREAD

**Issue by hikken** [orocrm/crm#261]
Hi i have a problem during orocrm 2.0 installation, after installation, i try to login page i was redirect into package installation but, i have more problem notice, warning and fatal error (see bellow url image)
[http://imgur.com/a/rrD3v](url) 
I'm trying to reinstall, update composer, drop database, but same result 

Can you help Me 

Notice : i have an instance of orocrm 1.10, is run fine

**Comment by manowark** [comment]
Hi, @hikken.
Please, give all steps that you did? What version of composer you use?

**Comment by hikken** [comment]
Hi thanks for your answer, 

My version of composer is  1.2.4

The  installation step : 
1er Download orocrm package and unzip files  
2e Run commande composer install --prefer-dist --no-dev 
3e Create Database
4e Run the Installation  with console with this command : php app/console oro:install --env=dev 

that's all

**Comment by manowark** [comment]
After update composer, please do all steps from first step.

**Comment by hikken** [comment]
@manowark Thanks for your advice, it's working fine !
