### ISSUE TITLE
Error when importing data 

### ISSUE THREAD

**Issue by kusgpt26** [orocrm/crm#265]
I have orocrm 2.0.0 installation. I create a custom entity and add address to that entity like contact in contact bundle.

Everything work properly except import system. When i import data to my custom entity and run `message-queue:consume`  it gives following error-

**[error] Consuming interrupted by exception. "A new entity was found through the relationship 'Example\Bundle\CustomBundle\Entity\CustomAddress#country' that was not configured to cascade persist operations for entity: . To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist  this association in the mapping for example @ManyToOne(..,cascade={"persist"})."**

Please reply if any suggestion.

Thanks!

**Comment by sadortun** [comment]
Related  / duplicates : 
https://github.com/orocrm/crm/issues/191 and https://github.com/orocrm/crm/issues/216

**Comment by mkudelya** [comment]
Hi @kusgpt26 

Try to add this option to your relation `cascade={"persist"}`. Here is an [example](https://github.com/orocrm/platform/blob/4c2271ce5c7bb37745bcc5dfd6083731a9741b67/src/Oro/Bundle/DataAuditBundle/Entity/AuditField.php#L23).

**Comment by kusgpt26** [comment]
Hi @mkudelya  

I have followed OroContactBundle concept in which  Asset is an entity in which AssetAddress is mapped as like Contact and ContactAddress.

The Entity Configuration is Like this ..

```
             /**
              * @var Collection
              *
              * @ORM\OneToMany(targetEntity="Custom\Bundle\AssetBundle\Entity\AssetAddress",
               *    mappedBy="owner", cascade={"all"}, orphanRemoval=true
              * )
              * @ORM\OrderBy({"primary" = "DESC"})
              *
               * @ConfigField(
               *      defaultValues={
               *        "entity"={
               *            "label"="hotelivate.asset.addresses.label"
               *          },
               *        "importexport"={
               *            "order"=150,
                *              "full"=true
                *        }
                *    }
                * )
               */
                public $addresses; 
```
AssetAddress entity extends 

       Oro\Bundle\AddressBundle\Entity\AbstractTypedAddress   

which is already mapped with country and region field inside vendor. I have followed strictly 
    OroContactBundle and all the things are very fine . It only creates problem in import action in which persistance problem of mapped entities(one-to-many or many-to-many) is comming. In Asset entity two fields assetAddress(one-to-many), and contacts(many-to-many) are available . contacts field is mapped to OroContactBundle by EntityExtendBundle migration script command.

My script command is like this 
 

         `$this->extendExtension->addManyToManyRelation(
            $schema,
            'custom_asset', // owning side table
            'contacts', // owning side field name
            'orocrm_contact', // inverse side table
            ['first_name'], // column names are used to show a title of related entity
            ['first_name'], // column names are used to show detailed info about related entity
            ['first_name'], // Column names are used to show related entity in a grid
            ['extend' => ['owner' => ExtendScope::OWNER_CUSTOM]]
        );
        $this->extendExtension->addManyToManyInverseRelation(
            $schema,
            'custom_asset', // owning side table
            'contacts', // owning side field name
            'orocrm_contact', // inverse side table
            'assets', // inverse side field name
            ['name'], // column names are used to show a title of owning side entity
            ['description'], // column names are used to show detailed info about owning side entity
            ['name'], // Column names are used to show owning side entity in a grid
            ['extend' => ['owner' => ExtendScope::OWNER_CUSTOM]]
        );`

It is working all except import action. I do't know from where i can include cascade = {"persist"} because $country and $region both are inside OroAddressBundle while $assets and $contacts  fields are mapped by migration command as written above . Please give me suggestion what  wrong i m doing .

**Comment by mkudelya** [comment]
@kusgpt26, in case an AssetAddress entity is extended, you can do the following inheritance, AbstractTypedAssetAddress and AbstractAssetAddress should fully repeat original classes (AbstractTypedAddress and AbstractAssetAddress), except that for the last entity you need to add a cascade = {"persist"} to the $country property:

Entity\AssetAddress.php

    <?php

     ...

    /**
     * AssetAddress
     *
     * @ORM\Table("oro_asset_address")
     * @ORM\Entity
     * @Config(
     *      defaultValues={
     *      ...
     *      }
     * )
     */
    class AssetAddress extends ExtendAssetAddress
    {
    }

Model\ExtendAssetAddress.php

    <?php

    ...    

    class ExtendAssetAddress extends AbstractTypedAssetAddress
    {
        public function __construct()
        {
        }
    }

Entity\AbstractTypedAssetAddress.php

    <?php
    
    ....
    
    /**
     * Typed Asset Address
     *
     * @ORM\MappedSuperclass
     */
    abstract class AbstractTypedAssetAddress extends AbstractAssetAddress implements PrimaryItem
    {
    }

Entity\AbstractAssetAddress.php

    <?php

    ...
    
    /**
     * AbstractAssetAddress
     * .........
     */
    abstract class AbstractAssetAddress implements EmptyItem, FullNameInterface, AddressInterface
    {
    }
