### ISSUE TITLE
app/console oro:message-queue:consume hundreds of processes

### ISSUE THREAD

**Issue by dmytro-butko** [orocrm/crm#266]
hey there,

fresh install, integrated with Magento 1.x, hundreds of processes like

_root     16075  0.0  0.0   4508   752 ?        Ss   Apr19   0:00 /bin/sh -c /usr/bin/php7.0 /srv/crm-application/app/console oro:message-queue:consume --env=prod >> /var/log/oro-consume.log
root     16078  0.5  7.2 625832 280212 ?       S    Apr19   5:00 /usr/bin/php7.0 /srv/crm-application/app/console oro:message-queue:consume --env=prod
root     22072  0.0  0.0   4508   816 ?        Ss   Apr19   0:00 /bin/sh -c /usr/bin/php7.0 /srv/crm-application/app/console oro:message-queue:consume --env=prod >> /var/log/oro-consume.log
root     22076  0.1  4.4 516284 170048 ?       S    Apr19   0:47 /usr/bin/php7.0 /srv/crm-application/app/console oro:message-queue:consume --env=prod_

the process is started every minute from CRON as per manual... 
obviously server is hanging after some time with OOM

_oro/redis-config	2.0.0-beta.1	MIT
oro/doctrine-extensions	1.1.1	MIT
oro/platform	2.1.0	MIT
oro/marketing	2.1.0	OSL-3.0
oro/crm-task-bundle	2.1.0	OSL-3.0
oro/crm-call-bundle	2.1.0	OSL-3.0
oro/calendar-bundle	2.1.0	OSL-3.0
oro/crm	2.1.0	OSL-3.0
oro/crm-mail-chimp	2.1.0	OSL-3.0
oro/crm-abandoned-cart	2.1.0	OSL-3.0
oro/crm-dotmailer	2.1.0	OSL-3.0
oro/crm-hangouts-call-bundle	2.1.0	OSL-3.0
oro/crm-magento-embedded-contact-us	2.1.0	OSL-3.0
oro/crm-zendesk	2.1.0	OSL-3.0
oro/platform-serialised-fields	2.1.0	OSL-3.0_

what could be the issue?
thanks in advance!

**Comment by sadortun** [comment]
@dmytro-butko FYI, the `oro:message-queue:consume` should not be started from CRON but from supervisord

See bullet # 7 at https://github.com/orocrm/crm-application#installation

**Comment by mbessolov** [comment]
And the Supervisord config example here - https://github.com/orocrm/platform/blob/master/src/Oro/Bundle/MessageQueueBundle/README.md#supervisord

**Comment by dmytro-butko** [comment]
oh cool thanks!
you may want to update installation guide..
i've got it here: https://www.orocrm.com/documentation/2.0/book/installation

![image](https://cloud.githubusercontent.com/assets/8305494/25212348/17f392c2-25cd-11e7-9987-2626f93cc215.png)

**Comment by mbessolov** [comment]
@dmytro-butko thanks for reporting. The documentation page has been fixed.
