### ISSUE TITLE
Date type form field submit default date

### ISSUE THREAD

**Issue by kusgpt26** [orocrm/crm#268]
Hi everyone,

I have an installation of Orocrm-2.0.0. I have created an entity named `Infrastructure` consisting of some date type field as follows- 

```
class Infrastructure
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    public $id;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="dateProjectStart", type="date", nullable=true)
     */
    private $dateProjectStart;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="dateOperational", type="date", nullable=true)
     */
    private $dateOperational;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="datePropertyClosed", type="date", nullable=true)
     */
    private $datePropertyClosed;
```
I have also created form for this entity.

```
class InfrastructureType extends AbstractType
{
  /**
   * {@inheritdoc}
   */
  public function buildForm(FormBuilderInterface $builder, array $options)
  {
      $builder
        ->add('dateProjectStart', 'oro_date', array('empty_value' => null,'required' => false))
        ->add('dateOperational', 'oro_date', array('empty_value' => null,'required' => false))
        ->add('datePropertyClosed', null, array('empty_value' => null))
 }
}
```
When i am submitting  this form without selecting any date then it saved current date in database . I don't understand why this happen. 

If  any suggestion please replay.

Thank!

**Comment by mkudelya** [comment]
Hi @kusgpt26 

Are you sure that the controller or form handler were not assigned the default value? I have tested your case on [TaskType](https://github.com/orocrm/OroCRMTaskBundle/blob/master/Form/Type/TaskType.php) (the form also contains the due_date field with the oro_date**time** type), and there were no issues. Also, please check your field in database and make sure that the field looks like: "field date DEFAULT NULL"

**Comment by kusgpt26** [comment]
@mkudelya  

Thanks for your replay.

I solved my issue. Actually there were no mistake in controller or form handler. The problem was in `view.htm.twig`  file where i put `date()` function which given current date in browser. 

 `{{ UI.renderProperty('Date Operationall'|trans, entity.infrastructure.dateOperational) | date() }}`

**Comment by mkudelya** [comment]
Good news!
I'm closing this issue.
