### ISSUE TITLE
Any plans with Caldav or Outlook sync?

### ISSUE THREAD

**Issue by projakethomas** [orocrm/crm#276]
Hi guys 

Great product.

Looking to use but would like to know if there is any plan in future for caldav sync?

Thanks

JT

**Comment by DimaSoroka** [comment]
Outlook sync is currently available with OroCRM Outlook Add-in as part of our enterprise edition offering, no plans for CalDAV support yet.

**Comment by projakethomas** [comment]
CalDav is a must feature in a CRM in this day of age, as Apple device prefer this, what kind of pricing is there on the outlook sync?

**Comment by DimaSoroka** [comment]
Thanks, we will consider adding this feature to our backlog, also contributions are welcome.
Our sales team will followup with you on pricing options.
