### ISSUE TITLE
Make State for the Netherlands not mandatory

### ISSUE THREAD

**Issue by falcovandermaden** [orocrm/crm#49]
The State field is at this point mandatory when choosing The Netherlands. Please change this to NOT mandatory. It's not common in The Netherlands to register state (province).

**Comment by nicola-stripe** [comment]
FYI - just received a support ticket where a user was confused about entering a "biz_state".

Ticket: https://notastartup.uservoice.com/admin/tickets/530204
Attachment image: https://s3.amazonaws.com/uploads.uservoice.com/assets/077/800/932/original/stripe_account.pdf?AWSAccessKeyId=14D6VH0N6B73PJ6VE382&Expires=1490352428&Signature=lSMcOIagVHSZrIS36IobPphvh5s%3D

+1 for making the dropdown optional or making the error message clearer

**Comment by diglin** [comment]
Same for Switzerland, please no mandatory state but for sure for almost all countries except USA :-) 

Cheers

**Comment by artml** [comment]
@falcovandermaden @nicola-stripe @diglin we have fixed this issue in 1.9.0 release so I am closing this ticket.
