### ISSUE TITLE
Magento Integration Error when Admin is Custom URL 

### ISSUE THREAD

**Issue by WinstonN** [orocrm/crm#60]
I am trying to connect oro-crm latest (1.3.1) to our Magento 1.8.1.0 website.
I set up the integration - as per this http://www.orocrm.com/blog/product-updates/integrate-magento-orocrm

I have a custom Magento admin URL

When I click "check connection" it comes back with Parameters are not valid!
In the log app/logs/prod.log I see

SOAP-ERROR: Parsing WSDL: Couldn't load from 'http://custom-admin.domain.com/index.php/api/v2_soap/index/?wsdl=1' : Attribute class redefined

Oro seems to try to connect to my custom admin url, even though admin url field is left empty - and the Url for the webservice is the frontend Url

The class vendor/oro/crm/src/OroCRM/Bundle/MagentoBundle/Controller/SoapController.php throws  an exception at L 49 $transport->init($transportEntity);
$transportEntity has the correct data

I hope this helps

**Comment by phpbugs** [comment]
Check the answer at http://magento.stackexchange.com/questions/15067/v2-soap-api-on-an-elastic-beanstalk-setup-with-a-separate-admin-server-stopped-w/15194#15194

**Comment by sergeyz** [comment]
Thanks, @phpbugs!

@WinstonN Thanks for report, reopen if you still have any issues with admin url
