### ISSUE TITLE
Magento Sync Issue

### ISSUE THREAD

**Issue by lance-spurgeon** [orocrm/crm#64]
Since we turned on the sync between magento and orocrm all went well until a week ago and it all stopped. I think there might be a bug. The error that I got was

Run sync for “Magento Web Store” integration.
Start processing “customer” connector
Looking for batch
found 3 entities
Loading entity by id: 2
Loading entity by id: 4
Loading entity by id: 45
Some entities were skipped due to warnings:A new entity was found through the relationship ‘OroCRM\Bundle\ContactBundle\Entity\Contact#accounts’ that was not configured to cascade persist operations for entity: Lance Spurgeon. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist this association in the mapping for example @ManyToOne(..,cascade={“persist”}).
Following customers were not imported: 2, 4, 45

… there is a load more info but not relevant to the error

Has anyone got an idea what this means and how I can fix it please

regards
Lance

**Comment by sergeyz** [comment]
Reworked magento integration available since 1.7, I think we can close this issue
