### ISSUE TITLE
do not allow contact csv import without an organization

### ISSUE THREAD

**Issue by lsmith77** [orocrm/crm#65]
since 1.4 when importing via CSV it is required to set an organization. however even without one, contacts are imported to the database, but they are then not shown in the contact list in the UI.

**Comment by hugeval** [comment]
Hi @lsmith77, thank you for your feedback. The issue does not appear within version 1.4.2. Please try 1.4.2 tag ```git checkout tags/1.4.2```

**Comment by lsmith77** [comment]
no time to test this atm .. but I assume it has been fixed since.
