### ISSUE TITLE
[Insight] Dependencies not installable

### ISSUE THREAD

**Issue by songofcode** [orocrm/crm#72]
> SensioLabsInsight was not able to install your Composer dependencies. If you need to customize files or run commands to make it work, you can edit your SensioLabsInsight project configuration to override the default "pre_composer_script" and/or "post_composer_script" settings.

```
Loading composer repositories with package information
Installing dependencies (including require-dev)

Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 79 bytes) in phar:///home/foobar/bin/composer.phar/src/Composer/DependencyResolver/Rule.php on line 62

```

---

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/0fb4b0eb-9dbd-4837-8332-c5af57e0be6d/analyses/9)_

**Comment by alsma-magecore** [comment]
Hey @songofcode !

Any updates on this ? Can we close it ?

**Comment by yurio** [comment]
Closed because we have not response.
