### ISSUE TITLE
Integration Page Security Bug

### ISSUE THREAD

**Issue by rodolfobandeira** [orocrm/crm#77]
Hi,
If one user that belongs to a specific organization change the URL passing other ID, we can access integration page with data from other organization.

Organization X:
http://YOUR_HOST/integration/update/6

User from Organization X, can access integration data from Organization Y just changing the id:
http://YOUR_HOST/integration/update/3

**Comment by yurio** [comment]
Hello @rodolfobandeira !

Fix for this issue will be commited in nearest release.
