### ISSUE TITLE
 can't view channel page on fresh installation without sample data 

### ISSUE THREAD

**Issue by tawfekov** [orocrm/crm#81]
I was trying to work on fresh installation but I got this error when I tried to view the channel page  on this url : http://oro.local/app_dev.php/channel

error message was : 
**An exception has been thrown during the rendering of a template ("An exception occurred while executing 'SELECT o0_.id AS id0, o0_.name AS name1, o0_.channel_type AS channel_type2, CASE WHEN o0_.status = 1 THEN 'enabled' ELSE 'disabled' END AS sclr3 FROM orocrm_channel o0_ WHERE o0_.organization_owner_id IN (1) AND o0_.organization_owner_id = 1 GROUP BY o0_.id ORDER BY o0_.name ASC':**

![500 internal server error](https://cloud.githubusercontent.com/assets/94997/4998971/2e73d660-69e6-11e4-9033-c8be6819fc58.png)

**Comment by arbitbet** [comment]
Thank you @tawfekov for your request.
What is DBMS do you use? MySQL and PostgreSQL works fine with this query.

**Comment by yurio** [comment]
Closed because it cannot reproduse.
