### ISSUE TITLE
[UX] Birthday date validation is not well adapted

### ISSUE THREAD

**Issue by jeanmonod** [orocrm/crm#98]
Trying to import a contact with a simple date could result in that error:

    Invalid datetime "1980-11-08", expected format Y-m-d\TH:i:sO.

There is no real raison to ask for a full datetime for a birthday, isn't it? Could be more friendly to accept both "Y-m-d\TH:i:sO" but also "Y-m-d" wdyt?

**Comment by synolia** [comment]
I think that this bug is fixed in the last version of Oro Platform (v1.6.1). Could you confirm ?
https://github.com/orocrm/platform/blob/1.6/src/Oro/Bundle/ImportExportBundle/Serializer/Normalizer/ConfigurableEntityNormalizer.php#L59

**Comment by DimaSoroka** [comment]
Issue was resolved.
