### ISSUE TITLE
Contact import fail with big CSV file 

### ISSUE THREAD

**Issue by jeanmonod** [orocrm/crm#99]
When importing a important file (3000 records, 800Ko), the import process end up with this error:

![contacts_-_customers](https://cloud.githubusercontent.com/assets/114489/5500967/daf111be-8750-11e4-8b93-08b2b84beefb.png)
Widget content loading failed

And I found this log in the apache error file:

    ==> /var/log/apache2/error.log <==
    [Fri Dec 19 05:36:35 2014] [error] [client 178.238.175.193] PHP Fatal error:  Maximum execution time of 30 seconds exceeded in
    /var/www/dev/vendor/oro/platform/src/Oro/Bundle/CacheBundle/Provider/ShortFileNameGeneratorTrait.php on line 21, referer: https://crm-staging.test.com/contact

**Comment by akuzmenko-magecore** [comment]
Hi @jeanmonod ,

Try increasing max_execution_time in your php.ini file.
I don't think that there is a big performance issue with import/export at the moment, but possibly will be improving it in future releases.

**Comment by rodolfobandeira** [comment]
Hi @jeanmonod  
With more than 5k rows, I was able to import data only using cli. 
```
oro:import:csv
```

**Comment by rodolfobandeira** [comment]
I decided to split my .csv based on number of the lines. Maximum 500 rows. Now the import using UI it's working fine.
```
split -l 500 file.csv file_splitted_
```

**Comment by artml** [comment]
Apparently this issue has been fixed so I'm closing it for now.
